### ISSUE TITLE
Failed to build miniaudio

### ISSUE THREAD

**Issue by sooyoung0321** [maxileith/homebridge-appletv-enhanced#14]
This is log...

```
[11/5/2023, 1:51:19 PM] [Apple TV Enhanced] Restarting Process...
[11/5/2023, 1:51:21 PM] [Apple TV Enhanced] Launched child bridge with PID 340102
[11/5/2023, 1:51:21 PM] The plugin "homebridge-appletv-enhanced" requires Node.js version of ^20.9.0 || ^18.18.2 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[11/5/2023, 1:51:22 PM] Registering platform 'homebridge-appletv-enhanced.AppleTVEnhanced'
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Loaded homebridge-appletv-enhanced v0.3.0-beta.4 child bridge successfully
[11/5/2023, 1:51:22 PM] Loaded 0 cached accessories from cachedAccessories.0E4BB0C62E8D.
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Platform: Finished initializing platform: Apple TV Enhanced
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Python check: Starting python check.
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Python check: plugin dir exists.
[11/5/2023, 1:51:22 PM] Homebridge v1.6.1 (HAP v0.11.1) (Apple TV Enhanced) is running on port 49206.
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Python check: Python 3.10.12 is installed and supported by the plugin.
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Python check: Virtual environment already exists.
[11/5/2023, 1:51:22 PM] [Apple TV Enhanced] Python check: Venv is using current system python version (3.10.12).
[11/5/2023, 1:51:28 PM] [Apple TV Enhanced] Python check: Pip is up-to-date
[11/5/2023, 1:51:31 PM] [Apple TV Enhanced] Python check: Python requirements are not satisfied. Installing them now.
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check: Collecting aiohttp==3.8.6 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 1))
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check:   Using cached aiohttp-3.8.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (7.7 kB)
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check: Collecting aiosignal==1.3.1 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 2))
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check:   Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check: Collecting annotated-types==0.6.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 3))
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check:   Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check: Collecting async-timeout==4.0.3 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 4))
[11/5/2023, 1:51:36 PM] [Apple TV Enhanced] Python check:   Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
[11/5/2023, 1:51:37 PM] [Apple TV Enhanced] Python check: Collecting attrs==23.1.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 5))
[11/5/2023, 1:51:37 PM] [Apple TV Enhanced] Python check:   Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
[11/5/2023, 1:51:37 PM] [Apple TV Enhanced] Python check: Collecting certifi==2023.7.22 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 6))
[11/5/2023, 1:51:37 PM] [Apple TV Enhanced] Python check:   Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
[11/5/2023, 1:51:38 PM] [Apple TV Enhanced] Python check: Collecting cffi==1.16.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 7))
[11/5/2023, 1:51:38 PM] [Apple TV Enhanced] Python check:   Using cached cffi-1.16.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (1.5 kB)
[11/5/2023, 1:51:38 PM] [Apple TV Enhanced] Python check: Collecting chacha20poly1305-reuseable==0.10.2 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 8))
[11/5/2023, 1:51:38 PM] [Apple TV Enhanced] Python check:   Using cached chacha20poly1305_reuseable-0.10.2-cp310-cp310-manylinux_2_35_aarch64.whl
[11/5/2023, 1:51:39 PM] [Apple TV Enhanced] Python check: Collecting charset-normalizer==3.3.1 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 9))
[11/5/2023, 1:51:39 PM] [Apple TV Enhanced] Python check:   Using cached charset_normalizer-3.3.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (33 kB)
[11/5/2023, 1:51:40 PM] [Apple TV Enhanced] Python check: Collecting cryptography==41.0.5 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 10))
[11/5/2023, 1:51:40 PM] [Apple TV Enhanced] Python check:   Using cached cryptography-41.0.5-cp37-abi3-manylinux_2_28_aarch64.whl.metadata (5.2 kB)
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check: Collecting frozenlist==1.4.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 11))
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check:   Using cached frozenlist-1.4.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.2 kB)
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check: Collecting idna==3.4 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 12))
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check:   Using cached idna-3.4-py3-none-any.whl (61 kB)
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check: Collecting ifaddr==0.2.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 13))
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check:   Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check: Collecting mediafile==0.12.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 14))
[11/5/2023, 1:51:41 PM] [Apple TV Enhanced] Python check:   Using cached mediafile-0.12.0-py3-none-any.whl.metadata (2.3 kB)
[11/5/2023, 1:51:42 PM] [Apple TV Enhanced] Python check: Collecting miniaudio==1.59 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 15))
[11/5/2023, 1:51:42 PM] [Apple TV Enhanced] Python check:   Using cached miniaudio-1.59.tar.gz (1.1 MB)
[11/5/2023, 1:51:42 PM] [Apple TV Enhanced] Python check:   Installing build dependencies: started
[11/5/2023, 1:51:55 PM] [Apple TV Enhanced] Python check:   Installing build dependencies: finished with status 'done'
[11/5/2023, 1:51:55 PM] [Apple TV Enhanced] Python check:   Getting requirements to build wheel: started
[11/5/2023, 1:51:58 PM] [Apple TV Enhanced] Python check:   Getting requirements to build wheel: finished with status 'done'
[11/5/2023, 1:51:58 PM] [Apple TV Enhanced] Python check:   Preparing metadata (pyproject.toml): started
[11/5/2023, 1:52:01 PM] [Apple TV Enhanced] Python check:   Preparing metadata (pyproject.toml): finished with status 'done'
[11/5/2023, 1:52:03 PM] [Apple TV Enhanced] Python check: Collecting multidict==6.0.4 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 16))
[11/5/2023, 1:52:03 PM] [Apple TV Enhanced] Python check:   Using cached multidict-6.0.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
[11/5/2023, 1:52:03 PM] [Apple TV Enhanced] Python check: Collecting mutagen==1.47.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 17))
[11/5/2023, 1:52:03 PM] [Apple TV Enhanced] Python check:   Using cached mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check: Collecting protobuf==4.24.4 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 18))
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check:   Using cached protobuf-4.24.4-cp37-abi3-manylinux2014_aarch64.whl.metadata (540 bytes)
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check: Collecting pyatv==0.14.4 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 19))
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check:   Using cached pyatv-0.14.4-py3-none-any.whl.metadata (6.1 kB)
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check: Collecting pycparser==2.21 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 20))
[11/5/2023, 1:52:05 PM] [Apple TV Enhanced] Python check:   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
[11/5/2023, 1:52:06 PM] [Apple TV Enhanced] Python check: Collecting pydantic==2.4.2 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 21))
[11/5/2023, 1:52:06 PM] [Apple TV Enhanced] Python check:   Using cached pydantic-2.4.2-py3-none-any.whl.metadata (158 kB)
[11/5/2023, 1:52:10 PM] [Apple TV Enhanced] Python check: Collecting pydantic_core==2.10.1 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 22))
[11/5/2023, 1:52:10 PM] [Apple TV Enhanced] Python check:   Using cached pydantic_core-2.10.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.5 kB)
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check: Collecting requests==2.31.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 23))
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check:   Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check: Collecting six==1.16.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 24))
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check:   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check: Collecting srptools==1.0.1 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 25))
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check:   Using cached srptools-1.0.1-py2.py3-none-any.whl (13 kB)
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check: Collecting tabulate==0.9.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 26))
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check:   Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check: Collecting typing_extensions==4.8.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 27))
[11/5/2023, 1:52:11 PM] [Apple TV Enhanced] Python check:   Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
[11/5/2023, 1:52:12 PM] [Apple TV Enhanced] Python check: Collecting urllib3==2.0.7 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 28))
[11/5/2023, 1:52:12 PM] [Apple TV Enhanced] Python check:   Using cached urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
[11/5/2023, 1:52:12 PM] [Apple TV Enhanced] Python check: Collecting yarl==1.9.2 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 29))
[11/5/2023, 1:52:12 PM] [Apple TV Enhanced] Python check:   Using cached yarl-1.9.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (262 kB)
[11/5/2023, 1:52:16 PM] [Apple TV Enhanced] Python check: Collecting zeroconf==0.119.0 (from -r /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/dist/requirements.txt (line 30))
[11/5/2023, 1:52:16 PM] [Apple TV Enhanced] Python check:   Using cached zeroconf-0.119.0-cp310-cp310-manylinux_2_35_aarch64.whl
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached aiohttp-3.8.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.0 MB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached cffi-1.16.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (446 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached charset_normalizer-3.3.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (135 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached cryptography-41.0.5-cp37-abi3-manylinux_2_28_aarch64.whl (4.2 MB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached frozenlist-1.4.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (226 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached mediafile-0.12.0-py3-none-any.whl (21 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached mutagen-1.47.0-py3-none-any.whl (194 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached protobuf-4.24.4-cp37-abi3-manylinux2014_aarch64.whl (310 kB)
[11/5/2023, 1:52:19 PM] [Apple TV Enhanced] Python check: Using cached pyatv-0.14.4-py3-none-any.whl (452 kB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Using cached pydantic-2.4.2-py3-none-any.whl (395 kB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Using cached pydantic_core-2.10.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.8 MB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Using cached requests-2.31.0-py3-none-any.whl (62 kB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check: Building wheels for collected packages: miniaudio
[11/5/2023, 1:52:20 PM] [Apple TV Enhanced] Python check:   Building wheel for miniaudio (pyproject.toml): started
[11/5/2023, 1:52:23 PM] [Apple TV Enhanced] Python check:   Building wheel for miniaudio (pyproject.toml): finished with status 'error'
[11/5/2023, 1:52:23 PM] [Apple TV Enhanced] Python check:   error: subprocess-exited-with-error    × Building wheel for miniaudio (pyproject.toml) did not run successfully.  │ exit code: 1  ╰─> [18 lines of output]      running bdist_wheel      running build      running build_py      creating build      creating build/lib.linux-aarch64-cpython-310      copying miniaudio.py -> build/lib.linux-aarch64-cpython-310      running build_ext      generating cffi module 'build/temp.linux-aarch64-cpython-310/_miniaudio.c'      creating build/temp.linux-aarch64-cpython-310      building '_miniaudio' extension      creating build/temp.linux-aarch64-cpython-310/build      creating build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310      aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -DMA_NO_RESOURCE_MANAGER=1 -DMA_NO_NODE_GRAPH=1 -DMA_NO_ENGINE=1 -I/tmp/pip-install-8vd1edsg/miniaudio_588d9195c418441ab9a2c0b13d958805 -I/tmp/pip-install-8vd1edsg/miniaudio_588d9195c418441ab9a2c0b13d958805 -I/var/lib/homebridge/appletv-enhanced/.venv/include -I/usr/include/python3.10 -c build/temp.linux-aarch64-cpython-310/_miniaudio.c -o build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310/_miniaudio.o -g1 -O3 -ffast-math      build/temp.linux-aarch64-cpython-310/_miniaudio.c:50:14: fatal error: pyconfig.h: No such file or directory         50 | #    include <pyconfig.h>            |              ^~~~~~~~~~~~      compilation terminated.      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1      [end of output]    note: This error originates from a subprocess, and is likely not a problem with pip.
[11/5/2023, 1:52:23 PM] [Apple TV Enhanced] Python check:   ERROR: Failed building wheel for mi
```
My device is `Libre Computer AML-S905X-CC`
OS is `Ubuntu 22.04.1 LTS`
Python version is `3.10.12`

**Comment by maxileith** [comment]
Hi @sooyoung0321 ,

this seem like it is related to issue #6. Please install the packages that are mentioned there and try again.

**Comment by sooyoung0321** [comment]
It's running on homebridge pi image. I updated node.js and homebrdige UI. But no luck. The same error. I'll not try updating all systems.

**Comment by sooyoung0321** [comment]
FYI, I tried to install the miniaudio module on the command prompt but it failed. Hmmmm.. not exactly the same error message but it seems like related.
```
ubuntu@aml-s905x-cc:~$ pip install miniaudio
Defaulting to user installation because normal site-packages is not writeable
Collecting miniaudio
  Downloading miniaudio-1.59.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 20, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-2x5tj5ww/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-2x5tj5ww/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-2x5tj5ww/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "build_ffi_module.py", line 819, in <module>
          ffibuilder = FFI()
        File "/tmp/pip-build-env-2x5tj5ww/overlay/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.16.0, located in '/tmp/pip-build-env-2x5tj5ww/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-aarch64-linux-gnu.so'.  The two versions should be equal; check your installation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sooyoung0321** [comment]
self resolving this issue lol.. In my case, `pip3 install --upgrade pip` resolved this issue. In the log file, it said "Python check: Pip is up-to-date" but it didn't look like that. This post helped. https://stackoverflow.com/questions/58552666/exception-version-mismatch-this-is-the-cffi-package-version-1-13-1

**Comment by maxileith** [comment]
@sooyoung0321 So the python checker is only checking if pip inside the virtual environment is uptodate. It does not check if the system pip is uptodate.

**Comment by maxileith** [comment]
Can you confirm that you had to update the system pip and not the virtualenv pip. Because, if you had to update the virtualenv pip that should be done by my plugin and this would be a bug ...

**Comment by sooyoung0321** [comment]
I only updated the system pip. I installed the python-venv today to it may be the latest version.
