### ISSUE TITLE
TypeError during Python check

### ISSUE THREAD

**Issue by dkkrause** [maxileith/homebridge-appletv-enhanced#156]
### Analysis

During home bridge startup the following exception appears in the logs:

### Expected Behavior

No exception

### Steps To Reproduce

Occurs during each Apple TV Enhanced startup on my system.

### Logs

```Markdown
[1/2/2024, 3:01:05 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 0851) is running on port 51334.
[1/2/2024, 3:01:05 AM] [Apple TV Enhanced] Python check: Python 3.9.2 is installed and supported by the plugin.
[1/2/2024, 3:01:05 AM] [Apple TV Enhanced] Python check: Virtual environment already exists.
[1/2/2024, 3:01:05 AM] [Apple TV Enhanced] Python check: Venv is using current system python version (3.9.2).
[1/2/2024, 3:01:05 AM] [Apple TV Enhanced] Python check: Checking if pip is up-to-date ...
[1/2/2024, 12:01:49 PM] [Apple TV Enhanced] Python check: Exception:
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 138, in run
    packages = self.get_outdated(packages, options)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 148, in get_outdated
    return [
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 150, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'Version'
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "tv",
        "video"
    ],
    "deviceStates": [
        "paused",
        "playing"
    ],
    "remoteKeysAsSwitch": [
        "down",
        "home",
        "left",
        "menu",
        "play_pause",
        "right",
        "select",
        "turn_off",
        "turn_on",
        "up",
        "volume_down",
        "volume_up"
    ],
    "customInputURIs": [],
    "discover": {
        "unicast": [],
        "blacklist": [],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "forceVenvRecreate": false,
    "logLevel": 3,
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: Debian 11.8
- Docker: N/A
- Homebridge: v1.7.0
- Apple TV Enhanced: v1.0.0
- Node: v20.10.0
- npm: 10.2.3
- Python: 3.9.2

**Comment by maxileith** [comment]
What does `/var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated` return?

**Comment by maxileith** [comment]
The problem seems to originate from the command `/var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated` which is executed during the python check.

I have not seen this before ... I would suggest to retry. Besides that, this seems to be an issue with pip, not Apple TV Enhanced.

You can try to recreate the virtual python environment. In order to do that, you can check the corresponding option in the Configuration of the Plugin in the Homebridge Config UI.

**Comment by dkkrause** [comment]
Looks like the same exception:

***@***.***:/etc $ /var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated
Exception:
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 138, in run
    packages = self.get_outdated(packages, options)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 148, in get_outdated
    return [
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 150, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'Version'
***@***.***:/etc $

Thanks, Don

On Jan 2, 2024, at 12:49 PM, Maximilian Leith ***@***.***> wrote:



What does /var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated return?

**Comment by dkkrause** [comment]
Recreating the virtual python environment seems to fix the problem, thanks.

Thanks, Don

On Jan 2, 2024, at 1:02 PM, Maximilian Leith ***@***.***> wrote:



The problem seems to originate from the command /var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated which is executed during the python check.

I have not seen this before ... I would suggest to retry. Besides that, this seems to be an issue with pip, not Apple TV Enhanced.

You can try to recreate the virtual python environment. In order to do that, you can check the corresponding option in the Configuration of the Plugin in the Homebridge Config UI.

**Comment by dkkrause** [comment]
Sorry, spoke too soon. Here’s another log snippet:

[1/2/2024, 1:42:06 PM] [Apple TV Enhanced] Python check: Exception:
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 138, in run
    packages = self.get_outdated(packages, options)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 148, in get_outdated
    return [
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pip/_internal/commands/list.py", line 150, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'Version'

[1/2/2024, 1:42:07 PM] [Apple TV Enhanced] Python check: Pip is up-to-date
[1/2/2024, 1:42:14 PM] [Apple TV Enhanced] Python check: Python requirements are not satisfied. Installing them now ...

This is happening each time I restart.

Thanks, Don

On Jan 2, 2024, at 1:02 PM, Maximilian Leith ***@***.***> wrote:



The problem seems to originate from the command /var/lib/homebridge/appletv-enhanced/.venv/bin/pip list --outdated which is executed during the python check.

I have not seen this before ... I would suggest to retry. Besides that, this seems to be an issue with pip, not Apple TV Enhanced.

You can try to recreate the virtual python environment. In order to do that, you can check the corresponding option in the Configuration of the Plugin in the Homebridge Config UI.

**Comment by maxileith** [comment]
Is your Python installation complete? Can you do a `sudo apt install full-python`?

**Comment by maxileith** [comment]
However, after the error above, the startup sequence of the plugin should continue.

**Comment by dkkrause** [comment]
It does seem to be working, I have one other small complaint. full-python doesn’t seem to exist from my machine’s perspective:

***@***.***:~ $ sudo apt install full-python
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package full-python
***@***.***:~ $

Thanks, Don

On Jan 2, 2024, at 2:56 PM, Maximilian Leith ***@***.***> wrote:



However, after the error above, the startup sequence of the plugin should continue.

**Comment by maxileith** [comment]
Sorry. It should be `python-full` ... my fault

**Comment by dkkrause** [comment]
Huh.

***@***.***:~ $ sudo apt install python-full
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-full
***@***.***:~ $

I do have both python and python3 installed, does that matter?

Thanks, Don

On Jan 2, 2024, at 3:59 PM, Maximilian Leith ***@***.***> wrote:



Sorry. It should be python-full ... my fault

**Comment by maxileith** [comment]
That should be no problem.

Can you check the version of pip on your system with `pip --version` and then post the output here?

After that, update pip with `pip install pip --upgrade`.

Than recreate the venv and restart.

**Comment by maxileith** [comment]
Please reply via GitHub directly or answer the E-Mails without including the previous message. I do not want to clean up the GitHub issue every time. Also formatting the logs in correct Markdown would be nice.

**Comment by dkkrause** [comment]
Ok, pip is not in my path. Might be installed but it’s not found with ‘which pip’

***@***.***:~ $ pip
-bash: pip: command not found
***@***.***:~ $

Sorry, may be a bit out of my element here, would pip have been installed as part of homebridge?

Thanks, Don

On Jan 2, 2024, at 4:14 PM, Maximilian Leith ***@***.***> wrote:



That should be no problem.

Can you check the version of pip on your system with pip --version and then post the output here?

After that, update pip with pip install pip --upgrade.

Than recreate the venv and restart.

**Comment by dkkrause** [comment]
OK, will do, sorry.

Thanks, Don

On Jan 2, 2024, at 4:17 PM, Maximilian Leith ***@***.***> wrote:



Please reply via GitHub directly or answer the E-Mails without including the previous message. I do not want to clean up the GitHub issue every time. Also formatting the logs in correct Markdown would be nice.

**Comment by maxileith** [comment]
try with `python3 -m pip --version` and `python3 -m pip list --outdated`

**Comment by maxileith** [comment]
My guess is that your pip is behaving different than expected since your system is rather outdated. I have changed the way the newest version of pip is determined in v1.0.1-0. Can you install this version of the plugin and check if it works?

**Comment by dkkrause** [comment]
Ran the two commands as suggested:

```
don@Dons-MBP ~ % python3 -m pip --version
pip 21.1.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
don@Dons-MBP ~ % python3 -m pip install pip --upgrade
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.1.3)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.6 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Successfully installed pip-23.3.2
don@Dons-MBP ~ %
```

... and still get the exception. I then installed v1.0.1-2. After the restart, during startup this exception occurred:

```
[1/3/2024, 7:21:41 AM] [Apple TV Enhanced] Python check: Downloading https://www.piwheels.org/simple/annotated-types/annotated_types-0.6.0-py3-none-any.whl (12 kB)
[1/3/2024, 7:21:42 AM] [Apple TV Enhanced] Python check: Collecting async-timeout==4.0.3 (from -r /usr/lib/node_modules/homebridge-appletv-enhanced/requirements.txt (line 4))
[1/3/2024, 7:21:42 AM] [Apple TV Enhanced] Python check:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/async-timeout/async_timeout-4.0.3-py3-none-any.whl

[1/3/2024, 7:21:43 AM] [Apple TV Enhanced] Python check: Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
[1/3/2024, 7:21:43 AM] [Apple TV Enhanced] Python check: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/attrs/

```

But everything seemed to come up OK, and it worked. I then restarted again. I realized that I had checked the Force Venv Recreation box and had forgotten to uncheck it. I figured this out because I saw the vent rebuilt in the logs each time I restarted. (would be nice if it unchecked itself .... ?)

However,  the change you madein v1.0.1-2 seems to have worked as the exception no longer occurs, thank you!
