### ISSUE TITLE
Pairing Code Not in Logs

### ISSUE THREAD

**Issue by Azariah98** [maxileith/homebridge-appletv-enhanced#208]
### Analysis

The log entry containing the pairing code to add my AppleTVs to HomeKit does not appear in the logs.

### Expected Behavior

I have successfully installed, configured, and paired my two AppleTVs inside of HOOBS. The logs show successful pairing and are updating with changes to the devices (New Active State: off, etc). Per the instructions, I should see a log entry similar to 

Please add [Apple TV Wohnzimmer (2)] manually in Home app. Setup Code: xxxx-xxxx

That log entry does not appear. 

### Steps To Reproduce

Pairing or restarting the plugin. 

### Logs

```console
1/26/2024, 2:20:32 AMAppletv Enhanced BridgeAppleTVEnhancedERROR[E] Apple TV  Patio (6C:4A:85:17:4D:5C): Rocket Remote: Traceback (most recent call last):
  File "/var/lib/hoobs/appletvenhancedbridge/appletv-enhanced/.venv/bin/atvremote", line 8, in <module>
1/26/2024, 2:20:32 AMAppletv Enhanced BridgeAppleTVEnhancedERROR[E] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Rocket Remote: Traceback (most recent call last):
  File "/var/lib/hoobs/appletvenhancedbridge/appletv-enhanced/.venv/bin/atvremote", line 8, in <module>
1/26/2024, 2:20:32 AMAppletv Enhanced BridgeAppleTVEnhancedERROR[E] Platform: Error: Unable to parse result U json: SyntaxError: Unexpected end of JSON input
1/26/2024, 2:20:32 AMAppletv Enhanced BridgeAppleTVEnhancedWARNING[W] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Rocket Remote: Lost connection. Trying to reconnect ...
1/26/2024, 2:20:32 AMAppletv Enhanced BridgeAppleTVEnhancedWARNING[W] Apple TV  Patio (6C:4A:85:17:4D:5C): Rocket Remote: Lost connection. Trying to reconnect ...
1/26/2024, 2:21:19 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Platform: Finished initializing platform: undefined
1/26/2024, 2:21:19 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Starting python check.
1/26/2024, 2:21:19 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: plugin dir exists.
1/26/2024, 2:21:20 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Python 3.9.2 is installed and supported by the plugin.
1/26/2024, 2:21:20 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Virtual environment already exists.
1/26/2024, 2:21:20 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Venv is using current system python version (3.9.2).
1/26/2024, 2:21:26 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Venv pip version: 23.3.2
1/26/2024, 2:21:26 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Checking if there is an update for venv pip ...
1/26/2024, 2:21:27 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Venv pip is up-to-date
1/26/2024, 2:21:31 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Python requirements are satisfied.
1/26/2024, 2:21:31 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Python check: Finished
1/26/2024, 2:21:31 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Platform: Starting device discovery ...
1/26/2024, 2:21:41 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Platform: Adding Apple TV  Livingroom (40:CB:C0:E9:0E:A0)
1/26/2024, 2:21:41 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Livingroom (40:CB:C0:E9:0E:A0): verifying credentials ...
1/26/2024, 2:21:41 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Platform: Adding Apple TV  Patio (6C:4A:85:17:4D:5C)
1/26/2024, 2:21:41 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Patio (6C:4A:85:17:4D:5C): verifying credentials ...
1/26/2024, 2:21:44 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Livingroom (40:CB:C0:E9:0E:A0): Credentials are still valid. Continuing ...
1/26/2024, 2:21:44 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Livingroom (40:CB:C0:E9:0E:A0): Exposing Apple TV as accessory of type Apple TV.
1/26/2024, 2:21:44 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Patio (6C:4A:85:17:4D:5C): Credentials are still valid. Continuing ...
1/26/2024, 2:21:44 AMAppletv Enhanced BridgeAppleTVEnhanced[I]  Patio (6C:4A:85:17:4D:5C): Exposing Apple TV as accessory of type Apple TV.
1/26/2024, 2:21:48 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Finished initializing
1/26/2024, 2:21:48 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Patio (6C:4A:85:17:4D:5C): Finished initializing
1/26/2024, 2:21:52 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Active State: off
1/26/2024, 2:21:52 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Current App: com.google.ios.youtube
1/26/2024, 2:21:53 AMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Patio (6C:4A:85:17:4D:5C): New Active State: off
1/26/2024, 12:19:47 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Active State: on
1/26/2024, 12:20:37 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Media Type State: video
1/26/2024, 12:20:37 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Current App: com.plexapp.plex
1/26/2024, 12:20:38 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: playing
1/26/2024, 12:22:54 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: paused
1/26/2024, 12:23:03 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: playing
1/26/2024, 12:26:05 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: paused
1/26/2024, 12:26:08 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: playing
1/26/2024, 12:42:34 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Media Type State: unknown
1/26/2024, 12:42:34 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): Current App: com.apple.TVMusic
1/26/2024, 12:42:34 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Device State: idle
1/26/2024, 1:42:44 PMAppletv Enhanced BridgeAppleTVEnhanced[I] Apple TV  Livingroom (40:CB:C0:E9:0E:A0): New Active State: off
```

### Configuration

```JSON
{
    "platform": "AppleTVEnhanced",
    "name": "Apple TV Enhanced"
}
```

### Environment

- OS: HOOBS
- Docker: 
  - Image Version: 
- Homebridge: 1.7.0
- Homebridge Config UI: HOOBS
- Storage Path: 
- Apple TV Enhanced: 
- Node: 
- npm: 
- Python: 
- pip: 
- HDMI hops: 
- HomePod as default speaker:

**Comment by maxileith** [comment]
Might be an issue with HOOBS. Do you have added an external accessory published by HOOBS before? Like a television or AV Receiver?

Besides that, the code is usually the one of the main homebridge bridge. Try that one.

Since publishing, generating and logging the code of external accessories is not in the scope of plugins but homebridge itself, this is not a big of homebridge-appletv-enhanced.

**Comment by Azariah98** [comment]
I've added plenty of accessories to HomeKit through HOOBS, but all of those come through their own bridges. The bridges are added using QR codes from the HOOBS client.

So my normal method for getting devices into HomeKit through HOOBS is:

plugin > Bridge > QR Code > HomeKit

Then the accessories are added automatically through the bridge.

The AppleTV plugin bridge shows in my list of QR codes, but I do not see any QRs for the AppleTVs themselves. I'm guessing this is different since you've turned them into bridges rather than accessories. Is there any way to generate those QR codes?

**Comment by Azariah98** [comment]
Both of the ATVs show in HOOBS as accessories, but I cannot find anywhere to get those codes.

**Comment by CardenB** [comment]
@maxileith , the readme states that the bridge pairing code should be logged, but it is not logged.

**Comment by maxileith** [comment]
@CardenB The code is not logged by the plugin itself but homebridge. So it is not a bug of the plugin. If HOOBS is not logging the code, this is a bug of HOOBS.

**Comment by CardenB** [comment]
Ohhh interesting. I see now. Thanks for clarifying.

**Comment by CardenB** [comment]
I see the pairing code. For hoobs, it is not logged (I hate hoobs) but it CAN be found here:
`/var/lib/hoobs/appletvenhancedbridge.persist/AccessoryInfo.[identifier].json` with "pin-code" key

There will be several in `/var/lib/hoobs/appletvenhancedbridge.persist/`, one for the primary bridge and then others for each apple tv. You can see the different display names in the JSON to differentiate them.

If you're feeling generous, you could add an additional log by searching this directory perhaps. But HOOBS should probably die anyway.

**Comment by CardenB** [comment]
```
for file in /var/lib/hoobs/appletvenhancedbridge.persist/AccessoryInfo.*.json; do
  echo "Processing $file"
  displayName=$(jq -r '.displayName' "$file")
  pincode=$(jq -r '.pincode' "$file")
  echo "displayName: $displayName"
  echo "pincode: $pincode"
  echo "" # Print a newline for better readability between files
done
```
Should log the information needed for hoobs devices.
