### ISSUE TITLE
Not able to progress past 'Not setting access level of Speakers & TVs in your homeapp to "Everybody"

### ISSUE THREAD

**Issue by JacobTyrrell** [maxileith/homebridge-appletv-enhanced#264]
### Current Situation

Trying to set up plugin.

Pairs with the TV fine, then discovery happens. Then this happens. 

I have enabled Speakers & TVs to Everyone, yet this error keeps occuring.

### Logs

```console
[20/02/2024, 18:29:16] [Apple TV Enhanced] [D] TV (XXXXXXXXXXXXX): Unable to execute request 10: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above
[20/02/2024, 18:29:16] [Apple TV Enhanced] [D] TV (XXXXXXXXX): Error: Unable to execute request 10: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at o (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:627)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[20/02/2024, 18:29:16] [Apple TV Enhanced] [W] TV (XXXXXXX): The plugin is receiving errors that look like you have not set the access level of Speakers & TVs in your home app to "Everybody" or "Anybody On the Same Network". Fix this and restart the plugin to continue initializing the Apple TV device. Enable debug logging to see the original errors.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv",
        "video"
    ],
    "deviceStates": [
        "idle",
        "loading",
        "paused",
        "playing",
        "seeking",
        "stopped"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "channel_down",
        "channel_up",
        "down",
        "home",
        "home_hold",
        "left",
        "menu",
        "next",
        "pause",
        "play",
        "play_pause",
        "previous",
        "right",
        "select",
        "skip_backward",
        "skip_forward",
        "stop",
        "turn_off",
        "turn_on",
        "top_menu",
        "up",
        "volume_down",
        "volume_up"
    ],
    "avadaKedavraAppAmount": 23,
    "disableVolumeControlRemote": false,
    "setTopBox": true,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 4,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "XXXXXXXXXXXXXX",
        "port": 52275
    },
    "platform": "AppleTVEnhanced"
}
```

### Environment

x

**Comment by JacobTyrrell** [comment]
OS: Raspbian GNU/Linux Bullseye (11)
Docker: false
Image Version: latest
Homebridge: latest
Homebridge Config UI: latest
Storage Path: /var/lib/homebridge
Apple TV Enhanced: latest
Node: v20.10.0
npm: 10.2.4
Python: 3.9.2
pip: (does not return a version)
HDMI hops: none (straight to TV)
HomePod as default speaker: only one speaker - dont think it is default

**Comment by JacobTyrrell** [comment]
![IMG_F23E577B44E0-1](https://github.com/maxileith/homebridge-appletv-enhanced/assets/33602551/09704281-7d79-422a-8361-c747212c5dbc)

**Comment by JacobTyrrell** [comment]
This was resolved. You also need to make sure the HomeKit in the AppleTV is also set to Everybody.
