### ISSUE TITLE
Cannot initiate Pairing on Apple TV on new install

### ISSUE THREAD

**Issue by jsiegenthaler** [maxileith/homebridge-appletv-enhanced#290]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

A new installation of Apple TV Enhanced cannot initiate pairing on the Apple TV. I have rebooted many times but no matter what, can never get the pin code display to appear on the Apple TV

### Logs

```console
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[27/02/2024, 18:40:44] [Apple TV Enhanced] [D] Platform: Executed didFinishLaunching callback
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Starting python check.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Python 3.9.2 is installed and supported by the plugin.
[27/02/2024, 18:40:44] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[27/02/2024, 18:40:45] [Apple TV Enhanced] [I] Python check: Venv is using current system python version (3.9.2).
[27/02/2024, 18:40:46] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.0
[27/02/2024, 18:40:46] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[27/02/2024, 18:40:47] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[27/02/2024, 18:40:48] [Apple TV Enhanced] [W] Python check: WARNING: The directory '/home/homebridge/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Python check: Finished
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] Platform: Setting the storage path of the PyATV instance to /var/lib/homebridge
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvscript path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript".
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvremote path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote".
[27/02/2024, 18:40:48] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[27/02/2024, 18:40:48] [Apple TV Enhanced] [D] Platform: Starting device discovery ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: finished multicast device discovery
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Found Apple TV Lounge (90:DD:5D:C5:8C:6B / 192.168.0.153).
[27/02/2024, 18:40:55] [Apple TV Enhanced] [I] Platform: Adding Apple TV Lounge (90:DD:5D:C5:8C:6B)
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Waiting for Apple TV Lounge (90:DD:5D:C5:8C:6B) to boot ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Accessory Config: {"name":"Apple TV Enhanced","mediaTypes":["music","tv"],"deviceStateDelay":0,"remoteKeysAsSwitch":["pause","play"],"avadaKedavraAppAmount":15,"disableVolumeControlRemote":false,"setTopBox":false,"discover":{"multicast":true},"forceVenvRecreate":false,"logLevel":4,"deviceSpecificOverrides":[{"overrideMediaTypes":false,"overrideDeviceStates":false,"overrideDeviceStateDelay":false,"deviceStateDelay":0,"overrideRemoteKeysAsSwitch":false,"overrideAvadaKedavraAppAmount":false,"avadaKedavraAppAmount":15,"overrideCustomInputURIs":false,"overrideDisableVolumeControlRemote":false,"disableVolumeControlRemote":false,"overrideSetTopBox":false,"setTopBox":false}],"platform":"AppleTVEnhanced"}
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Loaded credentials: undefined
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Loaded credentials: undefined
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Platform: Finished device discovery.
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Got empty credentials, initiating pairing process.
[27/02/2024, 18:40:55] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): Wait for the atvremote process to terminate
[27/02/2024, 18:40:55] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): Credentials are no longer valid. Need to repair ...
[27/02/2024, 18:40:55] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://192.168.0.100:42153/
[27/02/2024, 18:40:57] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): stdout: 2024-02-27 18:40:57 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/__init__.py", line 71, in error_handler
    return await func(*args, **kwargs)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 63, in start_pairing
    pairing_data = _get_pairing_data(resp)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/auth.py", line 33, in _get_pairing_data
    raise exceptions.AuthenticationError(stringify(tlv))
pyatv.exceptions.AuthenticationError: Error=BackOff, BackOff=9383s, SeqNo=M2
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 196, in pair
    await self._perform_pairing(pairing)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 206, in _perform_pairing
    await pairing.begin()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/companion/pairing.py", line 47, in begin
    await error_handler(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/__init__.py", line 77, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: Error=BackOff, BackOff=9383s, SeqNo=M2

[27/02/2024, 18:40:57] [Apple TV Enhanced] [W] Lounge (90:DD:5D:C5:8C:6B): Apple TV Lounge: Too many attempts. Waiting for 9388 seconds before retrying.
[27/02/2024, 18:40:57] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): 9388 seconds remaining.
[27/02/2024, 18:40:58] [Apple TV Enhanced] [D] Lounge (90:DD:5D:C5:8C:6B): 9387 seconds remaining.

```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "pause",
        "play"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:17:50:E5:71:23",
        "port": 57763
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

 NAME="Raspbian GNU/Linux"

### Operating System: Distribution Version

VERSION="11 (bullseye)"

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

4.55.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.2.4

### Node Version

v20.11.1

### NPM Version

10.2.4

### Python Version

3.9.2

### PIP Version

20.3.4

### HDMI Hops

AV Receiver

### Audio Output

no

### Same Subnet

yes

### Additional Context

I have tried many times but have never gotten the pairing display to appear on the Apple TV.
The URL in the logs (Enter the PIN that is currently displayed on the device here: http://192.168.0.100:42153/) always results in ERR_CONNECTION_REFUSED

**Comment by maxileith** [comment]
Yeah, the log might be a bit misleading.

So it is as follows:

* The plugin detects that there are no credentials
* The plugin initiates a pairing request and opens the Webserver on the URLs that is logged 
* The Apple TV declines the request since there were already to many attempts
* The plugin instantly closes the server
* The plugin waits for the back off time to pass
* The plugin initiates a new pairing request and opens the Webserver again
* The plugin waits 30 seconds (this is how long the pairing request is open)
  * You need to enter the code in this 30 seconds
* If not, you need to wait again

So the Webserver is only available when there is an active pairing request.

If you entered the back off loop. I would suggest to shutdown the plugin. Wait until you are certain that the back off time is over and then enable the plugin again. Be ready ton enter the code fast.

I might have to refactor the pairing process ...

**Comment by jsiegenthaler** [comment]
OK, 9388 seconds = 156m = 2.6 hours. I guess I'll shut down the plugin until tomorrow.

**Comment by jsiegenthaler** [comment]
My issue is that my Apple TV is in a different room from my PC, so if I reboot homebridge from my PC, and then walk to the TV room, the 30s can easily elapse before I get there.

I think you should update the pairing instructions to some something like:  

1. Install the plugin.
2. (optional) Enable the plugin to run as a child bridge. The benefit here is that the plugin is more isolated from other plugins, e.g. in case of a plugin crash, only the plugin will crash and not the whole homebridge.
**3. Important: Make sure you are in front of your Apple TV and ready to read the pairing code which will be displayed for a maximum of around XX seconds.**
4. Restart the homebridge.

**Comment by maxileith** [comment]
@jsiegenthaler have you successfully paired your Apple TV? Or do you need further assistance?

**Comment by jsiegenthaler** [comment]
HI. I just paired it now. You really have to be infront of the TV with an iPad and ready to quickly change the portnumber of Homebridge to type in the pin code.... easy to miss that step within the allotted time.

**Comment by Write** [comment]
Same issue here. New fresh install, already tried two codes  and got  the same error both times.
