### ISSUE TITLE
error pyatv.exceptions.BlockedStateError: apps is blocked

### ISSUE THREAD

**Issue by jondthompson** [maxileith/homebridge-appletv-enhanced#307]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

I saw the stack trace, not sure the ramifications to usability.

### Expected Behavior

not sure

### Steps To Reproduce

not sure

### Logs

```logs
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Python check: Starting python check.
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[3/7/2024, 1:07:23 PM] Homebridge v1.7.0 (HAP v0.11.1) (Apple TV Enhanced) is running on port 34658.
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Python check: Python 3.9.2 is installed and supported by the plugin.
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Python check: Venv is using current system python version (3.9.2).
[3/7/2024, 1:07:26 PM] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.0
[3/7/2024, 1:07:26 PM] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[3/7/2024, 1:07:26 PM] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[3/7/2024, 1:07:29 PM] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[3/7/2024, 1:07:29 PM] [Apple TV Enhanced] [I] Python check: Finished
[3/7/2024, 1:07:29 PM] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[3/7/2024, 1:07:37 PM] [Apple TV Enhanced] [I] Platform: Adding Apple TV Living Room (08:66:98:CA:C1:80)
[3/7/2024, 1:07:37 PM] [Apple TV Enhanced] [I] Living Room (08:66:98:CA:C1:80): verifying credentials ...
[3/7/2024, 1:07:37 PM] [Apple TV Enhanced] [I] Platform: Adding Apple TV Bike (C8:69:CD:2D:A9:12)
[3/7/2024, 1:07:37 PM] [Apple TV Enhanced] [W] Bike (C8:69:CD:2D:A9:12): Credentials are no longer valid. Need to repair ...
[3/7/2024, 1:07:37 PM] [Apple TV Enhanced] [W] Bike (C8:69:CD:2D:A9:12): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.46.209:42013/
[3/7/2024, 1:07:40 PM] [Apple TV Enhanced] [I] Living Room (08:66:98:CA:C1:80): Credentials are still valid. Continuing ...
[3/7/2024, 1:07:40 PM] [Apple TV Enhanced] [I] Living Room (08:66:98:CA:C1:80): Exposing Apple TV as accessory of type Apple TV.
[3/7/2024, 1:07:40 PM] [Apple TV Enhanced] [W] Bike (C8:69:CD:2D:A9:12): Apple TV Bike: Too many attempts. Waiting for 9738 seconds before retrying. The webpage to pair the Apple TV will become available again when the plugin is attempting the next pairing attempt.
[3/7/2024, 1:07:43 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): Finished initializing
[3/7/2024, 1:07:43 PM] Apple TV Living Room AC9D is running on port 45585.
[3/7/2024, 1:07:43 PM] Please add [Apple TV Living Room AC9D] manually in Home app. Setup Code: 285-53-604
[3/7/2024, 1:07:46 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): New Active State: on
[3/7/2024, 1:07:46 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): New Media Type State: unknown
[3/7/2024, 1:07:46 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): Current App: com.apple.TVMusic
[3/7/2024, 1:07:46 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): New Device State: idle
[3/7/2024, 1:12:36 PM] [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): New Active State: off
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at ClientAccessoryHandler.update (/usr/lib/node_modules/homebridge-unifi-occupancy/src/accessory_handler.ts:147:21)
    at UnifiOccupancyPlatform.updateAccessoryHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:374:29)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:362:12
    at Map.forEach (<anonymous>)
    at UnifiOccupancyPlatform.updateAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:360:22)
    at UnifiOccupancyPlatform.refreshAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:321:10)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:284:24
    at tryCatcher (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
[3/7/2024, 1:53:43 PM] [Apple TV Enhanced] [E] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote: Traceback (most recent call last):

[3/7/2024, 1:53:43 PM] [Apple TV Enhanced] [E] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 862, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 890, in _handle_device_command
    return await _exec_command(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 402, in cli
    await _handle_device_command(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 925, in _handle_device_command
    return await _exec_command(atv.apps, cmd, True, *cmd_args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: apps is blocked

>>> An error occurred, full stack trace above

[3/7/2024, 1:53:43 PM] [Apple TV Enhanced] [W] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote: Lost connection. Trying to reconnect ...
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at ClientAccessoryHandler.update (/usr/lib/node_modules/homebridge-unifi-occupancy/src/accessory_handler.ts:147:21)
    at UnifiOccupancyPlatform.updateAccessoryHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:374:29)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:362:12
    at Map.forEach (<anonymous>)
    at UnifiOccupancyPlatform.updateAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:360:22)
    at UnifiOccupancyPlatform.refreshAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:321:10)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:284:24
    at tryCatcher (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at ClientAccessoryHandler.update (/usr/lib/node_modules/homebridge-unifi-occupancy/src/accessory_handler.ts:147:21)
    at UnifiOccupancyPlatform.updateAccessoryHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:374:29)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:362:12
    at Map.forEach (<anonymous>)
    at UnifiOccupancyPlatform.updateAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:360:22)
    at UnifiOccupancyPlatform.refreshAccessories (/usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:321:10)
    at /usr/lib/node_modules/homebridge-unifi-occupancy/src/platform.ts:284:24
    at tryCatcher (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-unifi-occupancy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [
        "playing"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "left"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:AA:98:80:ED:AA",
        "port": 34658
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi OS

### Operating System: Distribution Version

11 (bullseye)"

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

4.55.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.2.5

### Node Version

20.11.1

### NPM Version

10.2.4

### Python Version

3.9.2

### PIP Version

23.3.2

### HDMI Hops

AV Receiver-> HDMI to coax adapter -> TV

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
It is not the Apple TV plugin that is throwing errors but the Unifi plugin.

**Comment by jondthompson** [comment]
Wrong.

This is the error I'm reporting.

` [Apple TV Enhanced] [I] Apple TV Living Room (08:66:98:CA:C1:80): New Active State: off
[3/11/2024, 8:19:35 AM] [Apple TV Enhanced] [E] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote: Traceback (most recent call last):

[3/11/2024, 8:19:35 AM] [Apple TV Enhanced] [E] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 862, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, storage, loop)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 890, in _handle_device_command
    return await _exec_command(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 402, in cli
    await _handle_device_command(
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 925, in _handle_device_command
    return await _exec_command(atv.apps, cmd, True, *cmd_args)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: apps is blocked

>>> An error occurred, full stack trace above

[3/11/2024, 8:19:35 AM] [Apple TV Enhanced] [W] Apple TV Living Room (08:66:98:CA:C1:80): Rocket Remote: Lost connection. Trying to reconnect `

**Comment by maxileith** [comment]
Sorry, I did not see that somehow between the Unifi errors. Why are you posting the Unifi errors here in the first place?

**Comment by jondthompson** [comment]
The unifi errors are in the logfile. I don't know why.  I initially gave you just the appropriate stack trace, but your bot wanted full logs from [3/7/2024, 1:07:23 PM] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced, so that is what I did. I turned log level 4 off because I don't know when the error happens until after the fact, and level 4 really causes log bloat.

**Comment by jondthompson** [comment]
And this is a Bug, not a support request. Even if it's something in my setup, your plugin should handle it without throwing an exception; preferably in a way that instructs me how to fix it without creating a "support request"

**Comment by maxileith** [comment]
> And this is a Bug, not a support request. Even if it's something in my setup, your plugin should handle it without throwing an exception; preferably in a way that instructs me how to fix it without creating a "support request"

I have switched it to a support request since I thought that the Unifi errors were the errors you were concerned about. 

You are right, this is a bug of the plugin ...

**Comment by maxileith** [comment]
It seems like the errors appears at a random time, is that correct?

Can you somehow bring that error in relation to some action you are doing? 

I have honestly never seen this error.

**Comment by jondthompson** [comment]
I can't. They just show up, and I haven't found any action that causes them. I'm watching for them now as they occurred several days before I created the bug report.

**Comment by maxileith** [comment]
What does happen after the Error? Does the Plugin crash and restart or do you see the following warning message?

`Rocket Remote: Trying to reconnect ...`

**Comment by maxileith** [comment]
> Even if it's something in my setup, your plugin should handle it without throwing an exception 

Errors happening within the pyatv process within the Rocket Remote class are actually handled. The handling is that the process is restarted once there occurs an error. The original stack trace is printed to the error log. But seeing this stack trace in the logs does not mean that the error is unhandled. 

When the rocket remote just reconnects, the plugin behaves as expected.

**Comment by nicholasrcupo** [comment]
Not sure if anyone else experienced this but wanted to comment in case they do. Seems like it is caused by installing virtualenv via pip when you already have the dependency satisfied by using homebridge via docker.
