### ISSUE TITLE
v1.3.0 Repeated Lost Connection Issue

### ISSUE THREAD

**Issue by Panic135** [maxileith/homebridge-appletv-enhanced#325]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

On version 1.3.0 I keep getting a continual error that says the below 

[3/19/2024, 12:53:31 AM] [Apple TV Enhanced] [D] Platform: Finished device discovery.
[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [D] Apple TV Lounge TV (A8:51:AB:A2:70:A3): Rocket Remote: app_list
[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [E] Apple TV Lounge TV (A8:51:AB:A2:70:A3): Rocket Remote: Connection lost, stack trace below

### Logs

```console
[3/19/2024, 12:53:31 AM] [Apple TV Enhanced] [D] Platform: Finished device discovery.
[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [D] Apple TV Lounge TV (REDACTED): Rocket Remote: app_list
[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [E] Apple TV Lounge TV (REDACTED): Rocket Remote: Connection lost, stack trace below:
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.8/site-packages/pyatv/core/protocol.py", line 56, in heartbeater
    await sender_func(message)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.8/site-packages/pyatv/protocols/airplay/ap2_session.py", line 94, in _send_feedback
    await self.rtsp.feedback()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.8/site-packages/pyatv/support/rtsp.py", line 248, in feedback
    return await self.exchange("POST", uri="/feedback", allow_error=allow_error)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.8/site-packages/pyatv/support/rtsp.py", line 320, in exchange
    raise TimeoutError(

[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [E] Apple TV Lounge TV (REDACTED): Rocket Remote: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote", line 8, in <module>
    sys.exit(main())
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 1003, in main
    return loop.run_until_complete(appstart(loop))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError

[3/19/2024, 12:53:34 AM] [Apple TV Enhanced] [W] Apple TV Lounge TV (REDACTED): Rocket Remote: Lost connection. Trying to reconnect ...
[3/19/2024, 12:53:39 AM] [Apple TV Enhanced] [D] Apple TV Lounge TV (REDACTED): recreating rocket remote
[3/19/2024, 12:53:39 AM] [Apple TV Enhanced] [D] Apple TV Lounge TV (REDACTED): Rocket Remote: creating
[3/19/2024, 12:53:40 AM] [Apple TV Enhanced] [D] Apple TV Lounge TV (REDACTED): Rocket Remote: Enter commands and press enter
Type help for help and exit to quit
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "deviceStates": [
                "playing"
            ],
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true,
                "blacklist": [
                    "REDACTED:C5"
                ]
            },
            "forceVenvRecreate": false,
            "logLevel": 4,
            "updateCheckLevel": "stable",
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "_bridge": {
                "username": "REDACTED",
                "port": 32829
            },
            "platform": "AppleTVEnhanced"
        }
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Ubuntu

### Operating System: Distribution Version

20.04.6 LTS (Focal Fossa)

### Docker

yes

### Docker Image

homebridge/homebridge

### Docker Image Tag

2024-01-08

### Homebridge Version

1.7.0

### Homebridge Config UI Version

4.55.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.3.0

### Node Version

v20.11.1

### NPM Version

10.2.4

### Python Version

3.8.10

### PIP Version

24.0

### HDMI Hops

Direct

### Audio Output

yes

### Same Subnet

yes

### Additional Context

[appletv-enhanced.log](https://github.com/maxileith/homebridge-appletv-enhanced/files/14644327/appletv-enhanced.log)

**Comment by maxileith** [comment]
When looking at the logs, it becomes clear that the errors does not happen continuously but once. After the remote process was closed by the error, the plugin has initiated another remote process and connected to the Apple TV successfully. The plugin behaves as expected.

**Comment by maxileith** [comment]
The plugin behaves like expected as the plugin is more or less a wrapper around pyatv. When pyatv loses connection, this is not in the scope of this plugin but pyatv. The only thing my plugin can really do is to initiate the pyatv process again.

> I could be wrong, did you design the plugin to lose connection every few minutes, upto 30 times each night?

No reason to be mean. No, it is obviously not desirable that pyatv loses connection 30 times a night.

The best thing to do in this case would be to [open an issue at pyatv](https://github.com/postlund/pyatv/issues).

**Comment by maxileith** [comment]
Created https://github.com/postlund/pyatv/issues/2376

**Comment by maxileith** [comment]
I forgot to write that in the previous message, but it is most likely a network problem on your side.
