### ISSUE TITLE
Infinite homebridge reboot

### ISSUE THREAD

**Issue by ceezet1** [maxileith/homebridge-appletv-enhanced#379]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

After the Apple TV is paired using the on screen code homebridge goes into an infinite boot because of an error with Apple TV enhanced (see log). It used to work perfectly on my raspberry pi. Until I got this error and now I have installed it on a Mac mini M1 and I have the same error and infinite boot loop.

### Expected Behavior

Well I expected no errors .

### Steps To Reproduce

1. Run normal installation as described for Mac OS
2.  Install python 11.? from python.org
3.  Discover Apple TV 4K (first gen)
4. pair with code
5. after rebooting error occurs

### Logs

```console
[4/16/2024, 10:37:45 PM] Homebridge v1.7.0 (HAP v0.11.2) (Homebridge 5657) is running on port 51568.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [D] Update check: The latest AppleTV Enhanced version (excluding betas) is 1.3.1
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.3.1
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [D] Update check: Starting update check interval.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Starting python check.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Python 3.11.9 is installed and supported by the plugin.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Venv is using current system python version (3.11.9).
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.0
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[4/16/2024, 10:37:45 PM] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [I] Python check: Finished
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [D] Platform: Setting the storage path of the PyATV instance to /Users/charleszwolsman/.homebridge
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvscript path to "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/bin/atvscript".
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [D] CustomPyATVInstance: Set atvremote path to "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/bin/atvremote".
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[4/16/2024, 10:37:46 PM] [Apple TV Enhanced] [D] Platform: Starting device discovery ...
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Platform: finished multicast device discovery
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Platform: Found Apple TV Woonkamer (90:DD:5D:D8:A3:1C / 192.168.50.60).
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [I] Platform: Adding Apple TV Woonkamer (90:DD:5D:D8:A3:1C)
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Platform: Waiting for Apple TV Woonkamer (90:DD:5D:D8:A3:1C) to boot ...
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Woonkamer (90:DD:5D:D8:A3:1C): Accessory Config: {"name":"Apple TV Enhanced","deviceStateDelay":0,"avadaKedavraAppAmount":15,"disableVolumeControlRemote":false,"setTopBox":false,"discover":{"multicast":true},"forceVenvRecreate":false,"logLevel":4,"updateCheckLevel":"stable","deviceSpecificOverrides":[{"overrideMediaTypes":false,"overrideDeviceStates":false,"overrideDeviceStateDelay":false,"deviceStateDelay":0,"overrideRemoteKeysAsSwitch":false,"overrideAvadaKedavraAppAmount":false,"avadaKedavraAppAmount":15,"overrideCustomInputURIs":false,"overrideDisableVolumeControlRemote":false,"disableVolumeControlRemote":false,"overrideSetTopBox":false,"setTopBox":false}],"platform":"AppleTVEnhanced"}
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Woonkamer (90:DD:5D:D8:A3:1C): Loaded credentials: 971fbadf927b0a4c1aebb36827d73292fae0221553716702eabca7325ba9669c:a61a8bcdf84ad103b220272344741e0d3abb67df5e17aa01c85a37acedb3a556:44424132374332442d353135332d344331432d393139332d393331394342304134364331:32363866363732362d363230302d343330362d383238382d363533343031613462396432
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [I] Woonkamer (90:DD:5D:D8:A3:1C): verifying credentials ...
[4/16/2024, 10:37:51 PM] [Apple TV Enhanced] [D] Platform: Finished device discovery.
[4/16/2024, 10:37:52 PM] [Apple TV Enhanced] [E] Woonkamer (90:DD:5D:D8:A3:1C): Unexpected atvremote response: 2024-04-16 22:37:52 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel
Traceback (most recent call last):
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 349, in _connect_rc
    await session.setup_remote_control()
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 79, in setup_remote_control
    await self._setup_event_channel(self.connection.remote_ip)
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 118, in _setup_event_channel
    resp = await self._setup(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 111, in _setup
    resp = await self.rtsp.setup(body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 176, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 293, in exchange
    resp = await self.connection.send_and_receive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/http.py", line 495, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 400: Bad RequestApp: Hit Tennis 3 (com.focusedapps.hittennis3), App: Crossy Road (com.hipsterwhale.crossy), App: Arcade (com.apple.Arcade), App: Vevo (com.vevo.iphone), App: App Store (com.apple.TVAppStore), App: Thuisbezorgd.nl (citymealprofile), App: Search (com.apple.TVSearch), App: NPO (nl.omroep.uitzendinggemist), App: Photos (com.apple.TVPhotos), App: Computers (com.apple.TVHomeSharing), App: Music (com.apple.TVMusic), App: JustWatchTV (com.justwatch.justwatch), App: TV (com.apple.TVWatchList), App: Dolby Summit (com.dolby.dolbysummit), App: Pool (com.byterun.pool), App: Moonlight (com.moonlight-stream.Moonlight), App: Strike! (com.touchmechanics.strike), App: NBA (com.nbaimd.gametime.universal), App: KickHero (com.loadcomplete.kickhero), App: Trailers (com.apple.movietrailers), App: Apple Events (com.apple.appleevents), App: NLZIET (nl.nlziet.nlziet), App: F1 TV (com.formula1.ott), App: YouTube (com.google.ios.youtube), App: Movies (com.apple.TVMovies), App: HBO Max (com.hbo.hbonow), App: Disney+ (com.disney.disneyplus), App: DS video (com.synology.DSvideo), App: FOX Sports (nl.eredivisie.app1), App: Infuse (com.firecore.infuse), App: Settings (com.apple.TVSettings), App: Netflix (com.netflix.Netflix), App: Tennis Champs TV (com.uprisinggames.tennistv), App: Viaplay (se.harbourfront.viasatondemand), App: Speedtest (com.ookla.speedtest), App: VLC (org.videolan.vlc-ios), App: NOS (nl.nos.app), App: Prime Video (com.amazon.aiv.AIVApp), App: discovery+ (com.kanal5.play), App: Keep Black (com.xinterium.tv.black), App: Podcasts (com.apple.podcasts), App: Steam Link (com.valvesoftware.SteamLink17)
[4/16/2024, 10:37:52 PM] [Apple TV Enhanced] [E] Woonkamer (90:DD:5D:D8:A3:1C): Error: Unexpected atvremote response: 2024-04-16 22:37:52 ERROR [pyatv.protocols.airplay]: Failed to set up remote control channel
Traceback (most recent call last):
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 349, in _connect_rc
    await session.setup_remote_control()
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 79, in setup_remote_control
    await self._setup_event_channel(self.connection.remote_ip)
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 118, in _setup_event_channel
    resp = await self._setup(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 111, in _setup
    resp = await self.rtsp.setup(body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 176, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 293, in exchange
    resp = await self.connection.send_and_receive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/charleszwolsman/.homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/http.py", line 495, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 400: Bad RequestApp: Hit Tennis 3 (com.focusedapps.hittennis3), App: Crossy Road (com.hipsterwhale.crossy), App: Arcade (com.apple.Arcade), App: Vevo (com.vevo.iphone), App: App Store (com.apple.TVAppStore), App: Thuisbezorgd.nl (citymealprofile), App: Search (com.apple.TVSearch), App: NPO (nl.omroep.uitzendinggemist), App: Photos (com.apple.TVPhotos), App: Computers (com.apple.TVHomeSharing), App: Music (com.apple.TVMusic), App: JustWatchTV (com.justwatch.justwatch), App: TV (com.apple.TVWatchList), App: Dolby Summit (com.dolby.dolbysummit), App: Pool (com.byterun.pool), App: Moonlight (com.moonlight-stream.Moonlight), App: Strike! (com.touchmechanics.strike), App: NBA (com.nbaimd.gametime.universal), App: KickHero (com.loadcomplete.kickhero), App: Trailers (com.apple.movietrailers), App: Apple Events (com.apple.appleevents), App: NLZIET (nl.nlziet.nlziet), App: F1 TV (com.formula1.ott), App: YouTube (com.google.ios.youtube), App: Movies (com.apple.TVMovies), App: HBO Max (com.hbo.hbonow), App: Disney+ (com.disney.disneyplus), App: DS video (com.synology.DSvideo), App: FOX Sports (nl.eredivisie.app1), App: Infuse (com.firecore.infuse), App: Settings (com.apple.TVSettings), App: Netflix (com.netflix.Netflix), App: Tennis Champs TV (com.uprisinggames.tennistv), App: Viaplay (se.harbourfront.viasatondemand), App: Speedtest (com.ookla.speedtest), App: VLC (org.videolan.vlc-ios), App: NOS (nl.nos.app), App: Prime Video (com.amazon.aiv.AIVApp), App: discovery+ (com.kanal5.play), App: Keep Black (com.xinterium.tv.black), App: Podcasts (com.apple.podcasts), App: Steam Link (com.valvesoftware.SteamLink17)
    at V.<anonymous> (/usr/local/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/device.ts:408:19)
    at Generator.next (<anonymous>)
    at o (/usr/local/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:627)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/16/2024, 10:37:52 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[4/16/2024, 10:37:57 PM] [HB Supervisor] Restarting Homebridge...
```

### Configuration

```JSON
"name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 4,
    "updateCheckLevel": "stable",
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Mac Os

### Operating System: Bits

64-bit

### Operating System: Distribution

Mac OS Sonoma 14.4.1

### Operating System: Distribution Version

14.4.1

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

v4.56.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.3.1

### Node Version

v20.12.2

### NPM Version

10.5.0

### Python Version

3.11.9

### PIP Version

12.2.4

### HDMI Hops

nothing

### Audio Output

no

### Same Subnet

yes

**Comment by BrandonHacks** [comment]
Ditto! Not working for me either now.. continuous boot looping

**Comment by ceezet1** [comment]
I fixed it! It was not a bug. It was Apple TV changing a setting after updating. What I did was go to airplay settings on the Apple TV  and set it to enable it for everyone on this network. Infinite boot solved here. Somehow after an update it was set to family members only
