### ISSUE TITLE
Loosing connection every few hours

### ISSUE THREAD

**Issue by crissmil** [maxileith/homebridge-appletv-enhanced#388]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hi! my appleTv is loosing connection every few hours and starts looping and asking for the pairing code. No any pairing code is launched on display, only restarting homebridge is enough to connect again. Any hints? Please see below:

```logs
[28/04/2024, 21:36:47] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: Traceback (most recent call last):

[28/04/2024, 21:36:47] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^

[28/04/2024, 21:36:47] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[28/04/2024, 21:36:48] [Apple TV Enhanced] [W] Apple TV (F0:F6:C1:35:20:68): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42059/
[28/04/2024, 21:36:49] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

[28/04/2024, 21:36:49] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: 
>>> An error occurred, full stack trace above
```

**Comment by crissmil** [comment]
after few days I noticed that above error is not related to my appletv. Actually the plugin is finding other devices from my network  and believes they are apple tvs and try to connect to them. So far I had to blackilist all my Sonos speakers and Samsung tvs. Every morning I find new connections attempts in hb log and add them to blacklist. I believe it should be a better fix for this issue.

**Comment by maxileith** [comment]
That's interesting. Could you send me the output of `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript scan`?

**Comment by crissmil** [comment]
hi! all I get is:


>>> %Run -c $EDITOR_CONTENT
usage: -c [-h] [--storage {file,none}] [--storage-filename STORAGE_FILENAME]
          [-i ID] [--protocol PROTOCOL] [-s SCAN_HOSTS] [--output OUTPUT]
          [--debug] [--dmap-credentials DMAP_CREDENTIALS]
          [--mrp-credentials MRP_CREDENTIALS]
          [--airplay-credentials AIRPLAY_CREDENTIALS]
          [--companion-credentials COMPANION_CREDENTIALS]
          [--raop-credentials RAOP_CREDENTIALS]
          command
-c: error: the following arguments are required: command

Process ended with exit code 2.

**Comment by maxileith** [comment]
You probably made a typo.

**Comment by crissmil** [comment]
sorry for my mistake...

{"result": "success", "datetime": "2024-05-02T22:28:35.295716+03:00", "devices": [{"name": "TV", "address": "10.0.216.21", "identifier": "34:67:D8:BB:8E:D1", "all_identifiers": ["34:67:D8:BB:8E:D1"], "device_info": {"mac": "34:67:D8:BB:8E:D1", "model": "Unknown", "model_str": "OLED65W9PLA", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 7000}]}, {"name": "Living Room", "address": "10.0.216.12", "identifier": "48:A6:B8:01:D3:49", "all_identifiers": ["48:A6:B8:01:D3:49", "48A6B801D349"], "device_info": {"mac": "48:A6:B8:01:D3:49", "model": "Unknown", "model_str": "Arc", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Cristi\u2019s MacBook Pro", "address": "10.0.216.15", "identifier": "F0:18:98:95:DA:08", "all_identifiers": ["F0:18:98:95:DA:08", "F0189895DA08"], "device_info": {"mac": "F0:18:98:95:DA:08", "model": "Unknown", "model_str": "MacBookPro15,1", "operating_system": "MacOS", "version": null}, "services": [{"protocol": "companion", "port": 51751}, {"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Apple TV", "address": "10.0.216.59", "identifier": "F0:F6:C1:35:20:68", "all_identifiers": ["F0:F6:C1:35:20:68", "F0F6C1352068"], "device_info": {"mac": "F0:F6:C1:35:20:68", "model": "Unknown", "model_str": "Roam SL", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Kitchen", "address": "10.0.216.46", "identifier": "94:9F:3E:C5:68:0B", "all_identifiers": ["94:9F:3E:C5:68:0B", "949F3EC5680B"], "device_info": {"mac": "94:9F:3E:C5:68:0B", "model": "Unknown", "model_str": "Beam", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Samsung Q60 Series (49)", "address": "10.0.216.53", "identifier": "00:7C:2D:CF:CA:32", "all_identifiers": ["00:7C:2D:CF:CA:32"], "device_info": {"mac": "00:7C:2D:CF:CA:32", "model": "Unknown", "model_str": "QRQ60", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 43216}]}, {"name": "AppleTV", "address": "10.0.216.11", "identifier": "6C:4A:85:38:55:63", "all_identifiers": ["78AA685E-DD6A-4850-97AF-2F13B0D236DB", "6C:4A:85:38:55:63", "6C4A85385563"], "device_info": {"mac": "6C:4A:85:38:55:63", "model": "Gen4K", "model_str": "Apple TV 4K", "operating_system": "TvOS", "version": "17.4"}, "services": [{"protocol": "companion", "port": 49153}, {"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Carla", "address": "10.0.216.65", "identifier": "C4:38:75:00:76:98", "all_identifiers": ["C4:38:75:00:76:98", "C43875007698"], "device_info": {"mac": "C4:38:75:00:76:98", "model": "Unknown", "model_str": "Move 2", "operating_system": "Unknown", "version": null}, "services": [{"protocol": "airplay", "port": 7000}, {"protocol": "raop", "port": 7000}]}, {"name": "Cristi\u2019s MacBook Pro", "address": "10.0.216.28", "identifier": "F0:18:98:95:DA:08", "all_identifiers": ["F0:18:98:95:DA:08", "F0189895DA08"], "device_info": {"mac": "F0:18:98:95:DA:08", "model": "Unknown", "model_str": "MacBookPro15,1", "operating_system": "MacOS", "version": null}, "services": [{"protocol": "airplay", "port": 7000}, {"protocol": "companion", "port": 51751}, {"protocol": "raop", "port": 7000}]}]}

**Comment by maxileith** [comment]
Sorry for the late response. Could you tell me which device has the MAC-Address F0:F6:C1:35:20:68? Is this actually an Apple TV?

**Comment by crissmil** [comment]
hi @maxileith , sorry for late reply. F0:F6:C1:35:20:68 is a Sonos Roam portable speaker.

**Comment by maxileith** [comment]
So currently my assumption is that the Sonos Roam somehow reports that it is one of the following models: 

```typescript
const ALLOWED_MODELS: string[] = [
    'Gen4',
    'Gen4K',
    'AppleTVGen4', // future proof since they will be renamed in pyatv
    'AppleTVGen4K',  // future proof since they will be renamed in pyatv
    'AppleTV4KGen2',
    'AppleTV4KGen3',
];
```

If a device reports that it is one of those models, my plugin assumes that this is an Apple TV. However, since your Sonos Roam is no Apple TV, the plugin fails to connect.

The output you have provided does not confirm that. I have added an additional check that checks whether or not the devices uses TvOS.

Can you install and test plugin version v1.4.1-1 and then let me know if this helps?

Also sorry about the stale bot. I am currently not very active. I have increased the time until an issue is beeing staled by the bot.

**Comment by crissmil** [comment]
Hi @maxileith ! I did install v1.4.1-1 and deleted all blacklists. Since 2 hours everything looks good. I'll revert tomorrow with confirmation if no more issues after 24 hrs... fingers crossed... Thanks!

**Comment by crissmil** [comment]
Hello again! Unfortunately the issue is still present:


[20/06/2024, 02:50:46] [Apple TV Enhanced] [E] Living Room (48:A6:B8:01:D3:49): stderr: 
>>> An error occurred, full stack trace above

[20/06/2024, 02:50:46] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:46] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[20/06/2024, 02:50:46] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:46] [Apple TV Enhanced] [W] Living Room (48:A6:B8:01:D3:49): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42012/
[20/06/2024, 02:50:46] [Apple TV Enhanced] [W] Apple TV (F0:F6:C1:35:20:68): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42059/
[20/06/2024, 02:50:47] [Apple TV Enhanced] [E] Kitchen (94:9F:3E:C5:68:0B): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:47] [Apple TV Enhanced] [E] Kitchen (94:9F:3E:C5:68:0B): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:47] [Apple TV Enhanced] [W] Kitchen (94:9F:3E:C5:68:0B): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42046/
[20/06/2024, 02:50:48] [Apple TV Enhanced] [E] Living Room (48:A6:B8:01:D3:49): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:48] [Apple TV Enhanced] [E] Living Room (48:A6:B8:01:D3:49): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:48] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:48] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:49] [Apple TV Enhanced] [W] Living Room (48:A6:B8:01:D3:49): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42012/
[20/06/2024, 02:50:49] [Apple TV Enhanced] [W] Apple TV (F0:F6:C1:35:20:68): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42059/
[20/06/2024, 02:50:49] [Apple TV Enhanced] [E] Kitchen (94:9F:3E:C5:68:0B): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:49] [Apple TV Enhanced] [E] Kitchen (94:9F:3E:C5:68:0B): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:49] [Apple TV Enhanced] [W] Kitchen (94:9F:3E:C5:68:0B): You need to pair your Apple TV before the plugin can connect to it. Enter the PIN that is currently displayed on the device here: http://10.0.216.27:42046/
[20/06/2024, 02:50:50] [Apple TV Enhanced] [E] Living Room (48:A6:B8:01:D3:49): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:50] [Apple TV Enhanced] [E] Living Room (48:A6:B8:01:D3:49): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

>>> An error occurred, full stack trace above

[20/06/2024, 02:50:51] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: Traceback (most recent call last):

[20/06/2024, 02:50:51] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^

[20/06/2024, 02:50:51] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 717, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 945, in _exec_command
    value = await tmp(*args)
            ^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 191, in pair
    pairing = await pair(
              ^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 173, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

[20/06/2024, 02:50:51] [Apple TV Enhanced] [E] Apple TV (F0:F6:C1:35:20:68): stderr: 
>>> An error occurred, full stack trace above

**Comment by maxileith** [comment]
Please send me debug logs as an attachment.

**Comment by crissmil** [comment]
Hi @maxileith , I don't' have the logs anymore because I put back all blacklisted macs and rebooted. My pi5 got really hot over night because of this child looping and I am not comfortable to stress it again. From my side I can live with this option to blacklist all other devices from my network...

**Comment by maxileith** [comment]
We do have the chance to resolve a bug here. It is basically impossible to kill a CPU with temperature since it will lower its TDP automatically. 90 degrees feel hot AF but it is not harmful for a CPU. However, in the end it is your Pi and your decision :)
