### ISSUE TITLE
Homebridge crashing

### ISSUE THREAD

**Issue by Supadone** [maxileith/homebridge-appletv-enhanced#47]
### Analysis

Hi

After the first start, the error message appears and the homebridge restarts...

### Expected Behavior

.

### Steps To Reproduce

.

### Logs

```Markdown
[14/11/2023, 11:58:26] Error: Unable to execute request L: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()
  File "/usr/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    async with async_timeout.timeout(timeout):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[14/11/2023, 11:58:27] Got SIGTERM, shutting down Homebridge...
[14/11/2023, 11:58:32] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

### Configuration

```JSON
{
            "mediaTypes": [
                "music",
                "video"
            ],
            "deviceStates": [
                "playing",
                "stopped"
            ],
            "remoteKeysAsSwitch": [],
            "discover": {
                "unicast": [],
                "blacklist": [
                    "192.168.1.48"
                ],
                "multicast": true
            },
            "name": "Apple TV Enhanced",
            "avadaKedavraAppAmount": 15,
            "forceVenvRecreate": false,
            "platform": "AppleTVEnhanced"
        }
```

### Environment

- OS: Raspberry Pi OS Bookworm
- Docker: false
- Homebridge: 1.7.0
- Apple TV Enhanced: v0.4.0
- Node: v20.5.1
- npm: 10.2.3
- Python: 3.11.2

**Comment by maxileith** [comment]
Can you provide more logs? From the start (`Finished initializing platform Apple TV Enhanced`) of the plugin until it crashes? Preferably with DEBUG enabled.

**Comment by Supadone** [comment]
Thank you for your quick response :)


```
[14/11/2023, 13:30:19] [Apple TV Enhanced] Initializing AppleTVEnhanced platform...
[14/11/2023, 13:30:19] [Apple TV Enhanced] Platform: Finished initializing platform: Apple TV Enhanced
[14/11/2023, 13:30:19] [Apple TV Enhanced] Platform: Executed didFinishLaunching callback
[14/11/2023, 13:30:19] [Apple TV Enhanced] 'linux 6.1.21-v8+' is supported by the plugin Homebridge Apple TV Enhanced.
[14/11/2023, 13:30:19] [Apple TV Enhanced] Python check: Starting python check.
[14/11/2023, 13:30:19] [Apple TV Enhanced] Python check: plugin dir exists.
Server listening on: http://<ip>:8282
[14/11/2023, 13:30:19] [Apple TV Enhanced] Python check: Python 3.11.2 is installed and supported by the plugin.
[14/11/2023, 13:30:19] [Apple TV Enhanced] Python check: Virtual environment already exists.
[14/11/2023, 13:30:19] [Apple TV Enhanced] Python check: Venv is using current system python version (3.11.2).
[14/11/2023, 13:30:51] [Apple TV Enhanced] Python check: Pip is up-to-date
[14/11/2023, 13:30:52] [Apple TV Enhanced] Python check: Python requirements are satisfied.
[14/11/2023, 13:30:52] [Apple TV Enhanced] Python check: Finished
[14/11/2023, 13:30:52] [Apple TV Enhanced] Platform: Setting the storage path of the PyATV instance to /var/lib/homebridge
[14/11/2023, 13:30:52] [Apple TV Enhanced] CustomPyATVInstance: Set atvscript path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript".
[14/11/2023, 13:30:52] [Apple TV Enhanced] CustomPyATVInstance: Set atvremote path to "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote".
[14/11/2023, 13:30:52] [Apple TV Enhanced] Platform: Starting device discovery ...
[14/11/2023, 13:30:52] [Apple TV Enhanced] Platform: Starting device discovery ...
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: finished multicast device discovery
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Found Apple TV Wohnzimmer (C0:95:6D:6F:B5:3B / 192.168.1.44).
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Adding Apple TV Wohnzimmer (C0:95:6D:6F:B5:3B)
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Waiting for Apple TV Wohnzimmer (C0:95:6D:6F:B5:3B) to boot ...
[14/11/2023, 13:31:00] [Apple TV Enhanced] Wohnzimmer (C0:95:6D:6F:B5:3B): Loaded credentials: 7a009925c701590de6899da47a35108bcb50d15b34650a8157497f9759791d7d:c4f17f5171b023f345e62a2b573b02c83035b0dbfe8934c928a79f402f63960e:34364334363843382d464237452d344539332d394536342d323337334143423034373846:31653763396163612d323164362d346231632d396662632d346631653330383538323130
[14/11/2023, 13:31:00] [Apple TV Enhanced] Wohnzimmer (C0:95:6D:6F:B5:3B): verifying credentials ...
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Found Apple TV Schlafzimmer (C0:95:6D:6C:4D:AA / 192.168.1.48).
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Apple TV Schlafzimmer (C0:95:6D:6C:4D:AA / 192.168.1.48) is on the blacklist. Skipping.
[14/11/2023, 13:31:00] [Apple TV Enhanced] Platform: Finished device discovery.
[14/11/2023, 13:31:07] Error: Unable to execute request 4: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()
  File "/usr/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    async with async_timeout.timeout(timeout):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutErrorTimeoutError>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[14/11/2023, 13:31:07] Got SIGTERM, shutting down Homebridge...
[14/11/2023, 13:31:12] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[14/11/2023, 13:31:16] [Homebridge UI] Terminal session ended.
[14/11/2023, 13:31:17] [HB Supervisor] Restarting Homebridge...
```

**Comment by maxileith** [comment]
Have you fulfulled this requirement from the README?

> The access of Speakers & TVs should be either set to "Everybody" or "Anybody On the Same Network" in the Home app

**Comment by Supadone** [comment]
Oh, I'm so sorry. That was exactly the mistake. Now everything works :)

**Comment by maxileith** [comment]
@Supadone don't worry. That is what I'm here for.
