### ISSUE TITLE
v1.5.1 libssl.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by haukee** [maxileith/homebridge-appletv-enhanced#513]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

Error on startup after Update from 1.5.0 to 1.5.1

### Expected Behavior

Normal Startup. 

### Steps To Reproduce

Upgrade from 1.5.0 to 1.5.1 via Hombridge GUI 

### Logs

```console
[29.7.2024, 12:39:26] Error: Unable to execute request 1O: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrpFile "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/cryptography/exceptions.py", line 9, in <module>from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
    at /usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15
    at Generator.next (<anonymous>)
    at o (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:984)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[29.7.2024, 12:39:27] Got SIGTERM, shutting down Homebridge...
[29.7.2024, 12:39:27] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/usr/lib/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/usr/lib/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/usr/lib/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "updateCheckLevel": "stable",
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "platform": "AppleTVEnhanced"
        }
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspbian GNU

### Operating System: Distribution Version

Linux Bullseye (11)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.4

### Homebridge Config UI Version

4.56.4

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.5.1

### Node Version

v20.16.0

### NPM Version

10.8.1

### Python Version

3.9.2

### PIP Version

20.3.4

### Audio Output

no

### Same Subnet

yes

### Additional Context

A downgrade to 1.5.0 fixed it

**Comment by maxileith** [comment]
Could you please send some more logs? Preferably from the start of the plugin until the error happens.

**Comment by ukiews** [comment]
Getting similar errors (I think):

```
Error: Unable to execute request 21: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15
    at Generator.next (<anonymous>)
    at o (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:984)
```

**Comment by nilthing9** [comment]
I'm seeing similar things too.
```
Error: Unable to execute request 59: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>
    from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/cryptography/exceptions.py", line 9, in <module>from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.3: cannot open shared object file: No such file or directory
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15
    at Generator.next (<anonymous>)
    at o (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:984)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

and a bit further down in my logs I'm seeing this, but I don't know if it is related:

```
AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

I role back to the previous version - all back to normal.

Hope this helps

**Comment by kloibs** [comment]
Similar error here, but rolling back to 1.5.0 doesn’t help; child bridge continually restarting. I’ll have to disable the child bridge for now to keep my Pi‘s temp under control:

`error:%20Unable%20to%20execute%20reguest%205W%3A%20Trace%20back%20(most%20recent%20call%20last)%3A%0AFile%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/bin/atvscript%22,%20line%0A5,%20in%20%E2%80%B9modus%0Ae%3Efrom%20pyatv.scripts.atvscript%20import%20main%20File%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/pyatv%0AInnit_.py%22%EF%BC%8C%20line%2026%EF%BC%8C%0Ain%20%3Cmodule%20%3E%0Afrom%20pyatv.protocols%0Aimport%20PROTOCOLS%0AFile%0A%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/pyatv%20/protocols/.%0A_init.%0A_py%22,%20line%2010,%20in%20%E2%80%B9modu%0A1e%3E%0Afrom%20pyatv.protocols%20import%20airplay%20as%20airplay_proto%0AFile%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/pyatv%20/protocols/airplay/%0Ainit_-py%22,%20line%2028,%0Ain%20%3Cmodule%3E%0Afrom%20pyatv.protocols%20import%20mrp%0AFile%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/pyatv%20/protocols/mrp/_%0Ainit_-Py%22,%20line%2014,%20in%20%3C%0Amodule%3E%0Afrom%20pyatv.auth.hap_srp%20import%20SRPAuth%0AHandler%0AFile%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/pyatv%20/auth/hap_srp.py%22,%20line%2010,%20in%20%E2%80%B9module%20%3E%0Afrom%20cryptography%20exceptions%20import%20In%20validsignature%0AFile%20%22/var/lib/homebridge/appletv-enhanc%20ed/.venv/lib/python3.9/site-packages/crypt%20ography/exceptions.py%22,%20line%209,%20in%20%E2%80%B9module%20%3E%0Afrom%20cryptography.hazmat.bindings._rus%0At%20import%20exceptions%20as%20rust_exceptions`

**Comment by kloibs** [comment]
@maxileith v1.5.2-0 solved it for me! Cheers!

**Comment by maxileith** [comment]
> @maxileith v1.5.2-0 solved it for me! Cheers!

Thanks for the fast reply @kloibs. Could you please let me know which OS you are using? Distro and version. My assumption is that your installation of openssl is too old.

**Comment by kloibs** [comment]
> > @maxileith v1.5.2-0 solved it for me! Cheers!
> 
> Thanks for the fast reply @kloibs. Could you please let me know which OS you are using? Distro and version. My assumption is that your installation of openssl is too old.

![IMG_6041](https://github.com/user-attachments/assets/7ee75145-df6b-44a1-a397-3d0e59442054)
![IMG_6042](https://github.com/user-attachments/assets/1b406298-dcf8-4dbb-8e84-7db723c4b1d5)

**Comment by maxileith** [comment]
Thanks for the info @kloibs. Seem that you and @haukee have in command that you are both using an outdated system.

Would be nice if @nilthing9 and @ukiews could send some system information.

**Comment by maxileith** [comment]
Additonally, could you please send me the output of  `openssl --version` @kloibs?

**Comment by Faisalthe01** [comment]
@maxileith v1.5.2-0 solved it for me too. thanks

**Comment by nilthing9** [comment]
v.1.5.2.0 Installed cleanly for me! No errors reported in the logs. Thanks for the quick update.

Current system: 
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
and 
`OpenSSL 1.1.1w  11 Sep 2023`

**Comment by haukee** [comment]
Kommt jetzt sauber hoch. Mega, ich danke dir.

**Comment by maxileith** [comment]
fyi, the next release will be updating the platform dependency to the latest version to officially support Python 3.12. However, the newest version of platform requires cryptography==43.0.0 which was causing problems with your outdated systems. I think it is time to update your systems.

**Comment by kloibs** [comment]
> fyi, the next release will be updating the platform dependency to the latest version to officially support Python 3.12. However, the newest version of platform requires cryptography==43.0.0 which was causing problems with your outdated systems. I think it is time to update your systems.

I just have Homebridge running on a Pi 3B+. So I’d have to upgrade the hardware?

**Comment by maxileith** [comment]
No the software. OpenSSL to be specific. However, the required OpenSSL version should be included in recent Debian / Raspian releases. So just update the OS to a current version.
