### ISSUE TITLE
Unable to run AppleTV Enhanced on tvOS 18

### ISSUE THREAD

**Issue by hist0rym4ker** [maxileith/homebridge-appletv-enhanced#671]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

Unable to connect to AppleTV after update to tvOS 18, continual boot on Homebridge

### Logs

```console
[08/10/2024, 12:03:10] [Apple TV Enhanced] Initializing AppleTVEnhanced platform...
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Update check: The update checker is configured to check for updates between 3:00 and 3:59, excluding betas. Auto updating is turned off.
Setup Payload:
X-HM://0023Z1DZAESN6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge  
                       
[08/10/2024, 12:03:10] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge C828) is running on port 51711.
[08/10/2024, 12:03:10] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[08/10/2024, 12:03:10] [Apple TV Enhanced] [S] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.9.0
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Python check: Starting python check.
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Python check: OpenSSL 3.0.11 is installed and compatible.
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Python check: Python 3.11.2 is installed and supported by the plugin.
[08/10/2024, 12:03:10] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Python check: Virtual environment is using the systems default python environment. Continuing ...
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.2
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[08/10/2024, 12:03:11] [Apple TV Enhanced] [S] Python check: Finished
[08/10/2024, 12:03:11] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[08/10/2024, 12:03:12] Error: Unable to execute request R: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
    at g (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.find (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/instance.ts:128:26)
    at AppleTVEnhancedPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/appleTVEnhancedPlatform.ts:114:67)
[08/10/2024, 12:03:12] Got SIGTERM, shutting down Homebridge...
```

### Configuration

```JSON
"name": "Apple TV Enhanced",
    "deviceStates": [
        "idle",
        "loading",
        "paused",
        "playing",
        "seeking",
        "stopped"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "turn_off",
        "turn_on"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false
        }
    ],
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspbian GNU/Linux

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

v1.8.4

### Homebridge Config UI Version

v4.60.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

v1.9.0

### Node Version

v20.18.0

### NPM Version

10.8.2

### Python Version

3.11.2

### PIP Version

23.0.1

### HDMI Hops

None

### Audio Output

no

### Same Subnet

yes

### Additional Context

[08/10/2024, 12:14:07] [Apple TV Enhanced] Initializing AppleTVEnhanced platform...
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Update check: The update checker is configured to check for updates between 3:00 and 3:59, excluding betas. Auto updating is turned off.
Setup Payload:
X-HM://0023Z1DZAESN6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
[08/10/2024, 12:14:07] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge C828) is running on port 51711.
[08/10/2024, 12:14:07] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[08/10/2024, 12:14:07] [Apple TV Enhanced] [S] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.9.0
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Python check: Starting python check.
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Python check: OpenSSL 3.0.11 is installed and compatible.
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Python check: Python 3.11.2 is installed and supported by the plugin.
[08/10/2024, 12:14:07] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Python check: Virtual environment is using the systems default python environment. Continuing ...
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.2
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[08/10/2024, 12:14:08] [Apple TV Enhanced] [S] Python check: Finished
[08/10/2024, 12:14:08] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[08/10/2024, 12:14:09] Error: Unable to execute request 22: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
    at g (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15)
    at Function.find (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/instance.ts:128:26)
    at AppleTVEnhancedPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/appleTVEnhancedPlatform.ts:114:67)
[08/10/2024, 12:14:09] Got SIGTERM, shutting down Homebridge...
[08/10/2024, 12:14:14] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/10/2024, 12:14:17] [Homebridge UI] Terminal session ended.
[08/10/2024, 12:14:19] [HB Supervisor] Restarting Homebridge...
[08/10/2024, 12:14:19] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[08/10/2024, 12:14:19] [HB Supervisor] Started Homebridge v1.8.4 with PID: 3375
[08/10/2024, 12:14:19] Loaded config.json with 0 accessories and 11 platforms.
[08/10/2024, 12:14:20] Loaded 0 cached accessories from cachedAccessories.
[08/10/2024, 12:14:20] ---
[08/10/2024, 12:14:20] Loaded plugin: homebridge-appletv-enhanced@1.9.0
[08/10/2024, 12:14:20] Registering platform 'homebridge-appletv-enhanced.AppleTVEnhanced'
[08/10/2024, 12:14:20] ---
[08/10/2024, 12:14:21] Disabled plugin: homebridge-google-nest-sdm@1.1.23
[08/10/2024, 12:14:21] ---
[08/10/2024, 12:14:21] Disabled plugin: homebridge-hubspace@1.3.0
[08/10/2024, 12:14:21] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-hue@0.13.70
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-irobot@2.1.16
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-leviton@2.0.1
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-meross@10.7.0
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-midea-platform@1.1.1
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-nest-cam@7.5.4
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Disabled plugin: homebridge-tplink-smarthome@8.0.3
[08/10/2024, 12:14:22] Disabled plugin: homebridge-wyze-smart-home@0.5.47
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] ---
[08/10/2024, 12:14:22] Loading 11 platforms...
[08/10/2024, 12:14:22] Ignoring config for the platform "Hubspace" in your config.json as the plugin "homebridge-hubspace" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "WyzeSmartHome" in your config.json as the plugin "homebridge-wyze-smart-home" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "TplinkSmarthome" in your config.json as the plugin "homebridge-tplink-smarthome" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "LevitonDecoraSmart" in your config.json as the plugin "homebridge-leviton" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "Nest-cam" in your config.json as the plugin "homebridge-nest-cam" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "homebridge-google-nest-sdm" in your config.json as the plugin "homebridge-google-nest-sdm" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "iRobotPlatform" in your config.json as the plugin "homebridge-irobot" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "midea-platform" in your config.json as the plugin "homebridge-midea-platform" has been disabled.
[08/10/2024, 12:14:22] Ignoring config for the platform "Meross" in your config.json as the plugin "homebridge-meross" has been disabled.
[08/10/2024, 12:14:22] [Apple TV Enhanced] Initializing AppleTVEnhanced platform...
[08/10/2024, 12:14:22] [Apple TV Enhanced] [I] Platform: Finished initializing platform: Apple TV Enhanced
[08/10/2024, 12:14:22] [Apple TV Enhanced] [I] Update check: The update checker is configured to check for updates between 3:00 and 3:59, excluding betas. Auto updating is turned off.
Setup Payload:
X-HM://0023Z1DZAESN6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
[08/10/2024, 12:14:22] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge C828) is running on port 51711.
[08/10/2024, 12:14:22] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[08/10/2024, 12:14:23] [Apple TV Enhanced] [S] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.9.0
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Starting python check.
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: OpenSSL 3.0.11 is installed and compatible.
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Python 3.11.2 is installed and supported by the plugin.
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Virtual environment already exists.
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Virtual environment is using the systems default python environment. Continuing ...
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Venv pip version: 24.2
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Checking if there is an update for venv pip ...
[08/10/2024, 12:14:23] [Apple TV Enhanced] [I] Python check: Venv pip is up-to-date
[08/10/2024, 12:14:24] [Apple TV Enhanced] [I] Python check: Python requirements are satisfied.
[08/10/2024, 12:14:24] [Apple TV Enhanced] [S] Python check: Finished
[08/10/2024, 12:14:24] [Apple TV Enhanced] [I] Platform: Starting device discovery ...
[08/10/2024, 12:14:24] Error: Unable to execute request 1E: Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript", line 5, in <module>from pyatv.scripts.atvscript import main
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 26, in <module>
    from pyatv.protocols import PROTOCOLS
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
    from pyatv.protocols import airplay as airplay_proto
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
    from pyatv.protocols import mrp
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 14, in <module>
    from pyatv.auth.hap_srp import SRPAuthHandler
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/auth/hap_srp.py", line 10, in <module>
    from cryptography.exceptions import InvalidSignature
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/cryptography/exceptions.py", line 9, in <module>from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
    at g (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:189:15)
    at Function.find (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/instance.ts:128:26)
    at AppleTVEnhancedPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/appleTVEnhancedPlatform.ts:114:67)
[08/10/2024, 12:14:24] Got SIGTERM, shutting down Homebridge...
[08/10/2024, 12:14:29] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/10/2024, 12:14:34] [HB Supervisor] Restarting Homebridge...

**Comment by maxileith** [comment]
duplicate of #621
