### ISSUE TITLE
Avada Kedavra is not working tvOS 18

### ISSUE THREAD

**Issue by dmytrokoren** [maxileith/homebridge-appletv-enhanced#673]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

Getting error provided in description.

### Expected Behavior

It should start closing all open applications

### Steps To Reproduce

Trigger the function via HomeKit nothing happens.
homebridge log showing error.

### Logs

```console
[10/10/2024, 08:08:51] [Apple TV Enhanced] [I] Living Room Apple TV (xx:xx:xx): Rocket Remote: Avada Kedavra
[10/10/2024, 08:08:52] [Apple TV Enhanced] [E] Living Room Apple TV (xx:xx:xx): Rocket Remote: Traceback (most recent call last):

[10/10/2024, 08:08:52] [Apple TV Enhanced] [E] Living Room Apple TV (xx:xx:xx): Rocket Remote:   File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 997, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 684, in cli_handler
    args = parser.parse_args()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1874, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[10/10/2024, 08:08:52] [Apple TV Enhanced] [E] Living Room Apple TV (xx:xx:xx): Rocket Remote:   File "/usr/lib/python3.11/argparse.py", line 1907, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2119, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2059, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.11/argparse.py", line 1983, in take_action
    action(self, namespace, argument_values, option_string)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/__init__.py", line 41, in __call__
    [ip_address(ip) for ip in ip_split]  # pylint: disable=expression-not-assigned
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/__init__.py", line 41, in <listcomp>
    [ip_address(ip) for ip in ip_split]  # pylint: disable=expression-not-assigned
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'xx:xx:xx' does not appear to be an IPv4 or IPv6 address

>>> An error occurred, full stack trace above
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false
        }
    ],
    "platform": "AppleTVEnhanced",
    "_bridge": {
        "username": "AA:BB:CC:DD:EE:FF",
        "port": xxxxx
    }
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi OS

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

v1.8.4

### Homebridge Config UI Version

v4.60.1

### Homebridge Storage Path

default

### Homebridge Apple TV Enhanced Version

1.9.0

### Node Version

v20.12.2

### NPM Version

10.5.0

### Python Version

3.11.2

### PIP Version

23.0.1

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
Fix is released with v1.9.1-0. Could you please give me some feedback if that version works on your side?

**Comment by dmytrokoren** [comment]
Yes, v1.9.1-0 fixed my issue! Thanks a lot.

If you have any suggestions on how to properly get the remote to appear in HomeKit, that would be great. I followed the installation instructions but am not sure if I missed something. Do I need to add the main Homebridge instance, or is the child bridge sufficient for HomeKit?

I had trouble getting the remote function to appear in HomeKit. After some trial and error, I'm not sure what exactly fixed it, but it's now working perfectly on both of my Apple TVs.

**Comment by maxileith** [comment]
> If you have any suggestions on how to properly get the remote to appear in HomeKit, that would be great. I followed the installation instructions but am not sure if I missed something. Do I need to add the main Homebridge instance, or is the child bridge sufficient for HomeKit?
> 
> I had trouble getting the remote function to appear in HomeKit. After some trial and error, I'm not sure what exactly fixed it, but it's now working perfectly on both of my Apple TVs.

The remote is exposed automatically. As soon as HomeKit is in the mood, you will find the remote control in the iOS Control Center. HomeKit sometimes takes its time and is very intransparent for the user.
