### ISSUE TITLE
Doesn't work on raspberry pi 4

### ISSUE THREAD

**Issue by mrota83** [maxileith/homebridge-appletv-enhanced#7]
Hi' 

i get this error. 
My homebridge is up to date i have latest version of your plugin too.
Thank you for your hard work on this plugin.

```log
[Apple TV Homebridge] Python check: Python 3.11.2 is installed and supported by the plugin.
[Apple TV Homebridge] Python check: Virtual environment already exists.
Error: ENOENT: no such file or directory, open '/var/lib/homebridge/appletv-enhanced/.venv/pyvenv.cfg'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.readFileSync (node:fs:445:35)
    at PythonChecker.isVenvPythonSystemPython (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/PythonChecker.ts:88:32)
    at PythonChecker.ensureVenvCreated (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/PythonChecker.ts:70:89)
    at PythonChecker.allInOne (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/PythonChecker.ts:38:20)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/src/appleTVEnhancedPlatform.ts:42:13)
```

**Comment by maxileith** [comment]
Can you give me the output of `ls -la /var/lib/homebridge/.venv/`?

**Comment by mrota83** [comment]
> Can you give me the output of `ls -la /var/lib/homebridge/appletv-enhanced/.venv/`?

How i do this ?

**Comment by maxileith** [comment]
You enter the command in the terminal. either via SSH or in the top right corner of the homebridge UI there are 3 dots where you can open a terminal.

**Comment by mrota83** [comment]
> ls -la /var/lib/homebridge/appletv-enhanced/.venv/

drwxr-xr-x 4 homebridge homebridge 4096  3 nov 21:15 .
drwxr-xr-x 3 homebridge homebridge 4096  3 nov 21:14 ..
drwxr-xr-x 2 homebridge homebridge 4096  3 nov 21:15 bin
drwxr-xr-x 3 homebridge homebridge 4096  3 nov 21:14 lib

**Comment by maxileith** [comment]
@mrota83 can you do `python3 -m venv /var/lib/homebridge/appletv-enhanced/.venv --clear` and send me a potential error output and do the `ls` command from before again and also send me that output?

**Comment by mrota83** [comment]
> @mrota83 can you do `python3 -m venv /var/lib/homebridge/appletv-enhanced/.venv --clear` and send me a potential error output and do the `ls` command from before again and also send me that output?

when i do `python3 -m venv /var/lib/homebridge/appletv-enhanced/.venv --clear` 
Error: [Errno 13] Permission denied: '__pycache__'

**Comment by maxileith** [comment]
Can you type in the terminal `whoami`? This should return the user with which your homebridge is running.

**Comment by mrota83** [comment]
> Can you type in the terminal `whoami`? This should return the user with which your homebridge is running.
> 
> Do that in the homebridge UI terminal, not via SSH!

homebridge

**Comment by maxileith** [comment]
Okay, are you using the homebridge image or the Raspberry PI OS image and have installed homebridge afterwards?

**Comment by mrota83** [comment]
> Okay, are you using the homebridge image or the Raspberry PI OS image and have installed homebridge afterwards?
> 
> I am using the homebridge image myself.
> 
> Overall, this seems to be a permission issue, not an issue regarding this plugin. Make sure that your homebridge user has sufficient rights to use python.

Im using raspberry pi os image and have installed homebridge afterwards

**Comment by maxileith** [comment]
@mrota83 what is the output of `groups` ?

**Comment by mrota83** [comment]
> @mrota83 what is the output of `groups homebridge` ?

sorry but how i check that ? 
how to create permission for my homebridge ?

**Comment by maxileith** [comment]
> ```logs 
> drwxr-xr-x 5 homebridge homebridge 4096  5 nov 08:43 .
> drwxr-xr-x 3 homebridge homebridge 4096  3 nov 21:14 ..
> drwxr-xr-x 2 root       root       4096  5 nov 07:56 bin
> drwxr-xr-x 3 root       root       4096  5 nov 07:56 include
> drwxr-xr-x 3 root       root       4096  5 nov 07:56 lib
> ```

In which folder is this? Is this `/var/lib/homebridge/appletv-enhanced/.venv`?

If so, execute `sudo rm -rf /var/lib/homebridge/appletv-enhanced`.

**Comment by maxileith** [comment]
> > @mrota83 what is the output of `groups homebridge` ?
> 
> sorry but how i check that ? 

Execute `groups homebridge` in the terminal.

**Comment by mrota83** [comment]
If so, execute sudo rm -rf /var/lib/homebridge/appletv-enhanced and restart the plugin.

ohhh we go tit !! its working :)

Thank you so much !!!

**Comment by mrota83** [comment]
Another error

Error: Unable to execute request 20: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()File "/usr/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await futasyncio.exceptions.CancelledErrorDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    async with async_timeout.timeout(timeout):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)

**Comment by mrota83** [comment]
[Apple TV Homebridge] Python check: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/pydantic-core/

**Comment by maxileith** [comment]
> If so, execute `sudo rm -rf /var/lib/homebridge/appletv-enhanced` and restart the plugin.

Did you do that?

**Comment by maxileith** [comment]
> ```logs
> [Apple TV Homebridge] Python check: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/pydantic-core/
> ```

This is not a problem

**Comment by maxileith** [comment]
Also ... do you have the current apt package of homebridge installed? 1.1.0?

**Comment by mrota83** [comment]
> > If so, execute `sudo rm -rf /var/lib/homebridge/appletv-enhanced` and restart the plugin.
> 
> Did you do that?

yes

**Comment by mrota83** [comment]
After restart the plugin it give me this error

Error: Unable to execute request 20: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 275, in _receive
    await semaphore.acquire()File "/usr/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await futasyncio.exceptions.CancelledErrorDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py", line 1092, in _connect
    await protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 146, in start
    self.device_info = await self.send_and_receive(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 262, in send_and_receive
    return await self._receive(identifier, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py", line 274, in _receive
    async with async_timeout.timeout(timeout):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at a (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)

it make my homebridge crash and force restart each times

**Comment by mrota83** [comment]
> Also ... do you have the current apt package of homebridge installed? 1.1.0?

 Homebridge v1.7.0 (HAP v0.11.1)

**Comment by maxileith** [comment]
I was talking about the apt package version, not the homebridge version itself.

**Comment by maxileith** [comment]
How did you configure access to TVs on the home app? It has to be Everyone or Anybody on the same network.

**Comment by mrota83** [comment]
> I was talking about the apt package version, not the homebridge version itself.

sorry latest apt package

**Comment by mrota83** [comment]
> How did you configure access to TVs in the home app? It has to be Everyone or Anybody on the same network.

Anybody on the same network

**Comment by maxileith** [comment]
Can you please try `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote -s xxx.xxx.xxx.xxx --protocol companion pair` where xxx.xxx.xxx.xxx is the ip of your Apple TV.

**Comment by mrota83** [comment]
> /var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote -s xxx.xxx.xxx.xxx --protocol companion pair

try first command

Enter PIN on screen: 
Pairing seems to have succeeded, yey!
You may now use these credentials: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by maxileith** [comment]
Can you now try `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript --id AA:BB:CC:DD:EE:FF --airplay-credentials xxxxxxxxx --companion-credentials xxxxxxx push_updates` with the credentials that you got from the command before.

**Comment by mrota83** [comment]
> Can you now try `/var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript --id AA:BB:CC:DD:EE:FF --airplay-credentials xxxxxxxxx --companion-credentials xxxxxxx push_updates` with the credentials that you got from the command before.

get this

Failed to set up remote control channel
Traceback (most recent call last):
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/__init__.py", line 349, in _connect_rc
    await session.setup_remote_control()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 79, in setup_remote_control
    await self._setup_event_channel(self.connection.remote_ip)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 118, in _setup_event_channel
    resp = await self._setup(
           ^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/airplay/ap2_session.py", line 111, in _setup
    resp = await self.rtsp.setup(body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 176, in setup
    return await self.exchange("SETUP", headers=headers, body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/rtsp.py", line 293, in exchange
    resp = await self.connection.send_and_receive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/http.py", line 495, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: RTSP/1.0 method SETUP failed with code 400: Bad Request
{"result": "failure", "datetime": "2023-11-05T17:34:56.941141-05:00", "exception": "", "stacktrace": "Traceback (most recent call last):\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py\", line 275, in _receive\n    await semaphore.acquire()\n  File \"/usr/lib/python3.11/asyncio/locks.py\", line 387, in acquire\n    await fut\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 391, in appstart\n    args.output(await _handle_command(args, abort_sem, storage, loop)),\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvscript.py\", line 271, in _handle_command\n    atv = await connect(config, loop, storage=storage)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py\", line 155, in connect\n    await atv.connect()\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py\", line 684, in connect\n    if await setup_data.connect():\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/__init__.py\", line 1092, in _connect\n    await protocol.start()\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py\", line 146, in start\n    self.device_info = await self.send_and_receive(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py\", line 262, in send_and_receive\n    return await self._receive(identifier, timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/mrp/protocol.py\", line 274, in _receive\n    async with async_timeout.timeout(timeout):\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py\", line 141, in __aexit__\n    self._do_exit(exc_type)\n  File \"/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/async_timeout/__init__.py\", line 228, in _do_exit\n    raise asyncio.TimeoutError\nTimeoutError\n"}

**Comment by maxileith** [comment]
Have you had a connection with that Apple TV before and than deleted the pyatv from the connected devices on your Apple TV? If so ... `rm ~/.pyatv.conf`

**Comment by mrota83** [comment]
ok don't know what happen but updated your plugin to 0.31 beta-1 all is working fine

**Comment by maxileith** [comment]
@mrota83 Nice, basically what I have just told you to do manually, v0.3.0-beta.1 is doing automatically.

Thank you for this long conversation. With your feedback you have made this fix possible.

**Comment by mrota83** [comment]
> @mrota83 Nice, basically what I have just told you to do manually, v0.3.1-beta.1 is doing automatically.
> 
> Thank you for this long conversation. With your feedback you have made this fix possible.

Thank you for your patience and your time.
