### ISSUE TITLE
Cross Subnet incompatability

### ISSUE THREAD

**Issue by failbit** [maxileith/homebridge-appletv-enhanced#8]
It is not possible to complete the pairing if the ATV is in a different subnet than HomeBridge. its a known issue for pyatv, see here: 
 https://github.com/postlund/pyatv/issues/628#issuecomment-626382556 for reference. 

I guess after detecting the ATV, you are trying to pair via IP, which will not work in this case. See: https://github.com/maxileith/homebridge-appletv-enhanced/blob/946657816da694642c9fd5f8e7cc0ae06774e870/src/appleTVEnhancedAccessory.ts#L733 

Maybe its possible to pair via name/unique identifier instead?

**Comment by maxileith** [comment]
Hi @failbit ,

thank you for your enhancement request. I do not have a setup with multiple subnets. Have you tested if `atvremote --id AA:BB:CC:DD:EE:FF --protocol companion pair` instead of the ip variant works over different subnets?

**Comment by failbit** [comment]
Hi @maxileith ! Thanks for your quick response. I can confirm, that <3atvremote --id AA:BB:CC:DD:EE:FF --protocol companion pair" immediately works (pin on screen and after): 

Pairing seems to have succeeded, yey!

**Comment by maxileith** [comment]
@failbit Can you paste the credentials in the `/var/lib/homebridge/appletv-enhanced/AABBCCDDEEFF/credentials.txt` file and restart the plugin to see if everything works across your multiple subnets just to be completely sure :) 

BTW, appreciating that you are looking into this plugin in such detail <3

**Comment by maxileith** [comment]
Ah sorry, I did not read your message very concentrated.

> Pairing seems to have succeeded, yey!

That implies that you have already used it in my plugin since it is a lot message from the plugin ...

Is everything else already working across the multiple subnets?

**Comment by failbit** [comment]
I did manually paired it with "atvremote --id AA:BB:CC:DD:EE:FF --protocol companion pair" and it succeeded. It returned credentials, which I then saved in /var/lib/homebridge/appletv-enhanced/C0956D5F9F86/credentials.txt 

Afterwards I restarted homebrigem but receive this error: 

[11/4/2023, 8:04:22 PM] [Apple TV Enhanced] Python check: Finished
[11/4/2023, 8:04:22 PM] [Apple TV Enhanced] Platform: Starting device discovery ...
[11/4/2023, 8:04:31 PM] [Apple TV Enhanced] Platform: Adding Apple TV AppleTV Wohnzimmer (AA:BB:CC:DD:EE:FF)
[Apple TV AppleTV Wohnzimmer@@Firmware Revision] Characteristic not in required or optional characteristic section for service Television. Adding anyway.
[11/4/2023, 8:04:38 PM] Error: Unexpected atvremote response: 2023-11-04 20:04:38 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network
    at V.<anonymous> (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/device.ts:392:19)
    at Generator.next (<anonymous>)
    at a (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)



---
Mac-Adress in Output is obfuscated.

**Comment by maxileith** [comment]
@failbit thanks for the logs.

Is homebridge crashing after the stacktrace or does it continue to run?

**Comment by failbit** [comment]
SIGTERM, then crash: 

[11/4/2023, 8:11:14 PM] Got SIGTERM, shutting down Homebridge...

**Comment by maxileith** [comment]
Okay, so that atvscript is not finding any Apple TVs makes kind of sense because your Apple TV is in another subnet. However, it's weird that the error is not catched here: https://github.com/maxileith/homebridge-appletv-enhanced/blob/c83a7130d1d966e7951160a2ef2d20bb8d2fe3e5/src/appleTVEnhancedPlatform.ts#L73

Definitely need to take a look at this.

**Comment by failbit** [comment]
Yes and it is not that unusual to have ATV as an IOT-Device and Homebrdige in different Subnets to isolate each other. It would be awesome to make your plugin usable in this scenario. 

atvremote standalone is working to control the ATV in the other subnet.

**Comment by maxileith** [comment]
@failbit Can you please delete the `credentials.txt` file that you have created manual before. Than try the pairing process with version v0.3.0-beta.5.

**Comment by failbit** [comment]
I get the PIN on the ATV. Good so far! 

But then:

[11/6/2023, 8:29:31 PM] [Apple TV Enhanced] Apple TV AppleTV Wohnzimmer (AA:BB:CC:DD:EE:FF): Paring was successful. Add it to your home in the Home app: com.apple.home://launch
[11/6/2023, 8:29:38 PM] Error: Unexpected atvremote response: 2023-11-06 20:29:38 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network
    at V.<anonymous> (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/device.ts:392:19)
    at Generator.next (<anonymous>)
    at a (/usr/lib/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:626)
[11/6/2023, 8:29:38 PM] Got SIGTERM, shutting down Homebridge...

**Comment by maxileith** [comment]
I have expected that, just wanted to know if it the pairing work so far ...

**Comment by maxileith** [comment]
Hi @IAmChrisAMA,

in order for the plugin to work over different subnets, all `atvremote` and `atvscript` commands that are executed in the background need to be started with the `--id` option instead of the `--scan-hosts` option, e.g. here:

https://github.com/maxileith/homebridge-appletv-enhanced/blob/b2f95c255fbbb5e6130e042807e32f60822fe543/src/appleTVEnhancedAccessory.ts#L1010

However, a lot of the processes are initiated by the library `@sebbo2002/node-pyatv`. So in order to make this plugin cross subnet compataible, I would suggest by making the library cross subnet compataible and opening a PR [over there](https://github.com/sebbo2002/node-pyatv) first. Then you or I can continue with the plugin itself.

**Comment by IAmChrisAMA** [comment]
> Hi @IAmChrisAMA,
> 
> in order for the plugin to work over different subnets, all `atvremote` and `atvscript` commands that are executed in the background need to be started with the `--id` option instead of the `--scan-hosts` option, e.g. here:
> 
> https://github.com/maxileith/homebridge-appletv-enhanced/blob/b2f95c255fbbb5e6130e042807e32f60822fe543/src/appleTVEnhancedAccessory.ts#L1010
> 
> However, a lot of the processes are initiated by the library `@sebbo2002/node-pyatv`. So in order to make this plugin cross subnet compataible, I would suggest by making the library cross subnet compataible and opening a PR [over there](https://github.com/sebbo2002/node-pyatv) first. Then you or I can continue with the plugin itself.

Thanks for the heads up. I've gone and setup an alternative Homebridge instance on the same subnet to use it for the time being.

It's not ideal but works. 

Alternate question (not really appropriate to put in this conversation), is there no way to make 3rd Party apps work with the sensors because it's considered an Apple TV rather than button and sensors? I can make a new thread.

**Comment by maxileith** [comment]
> Alternate question (not really appropriate to put in this conversation), is there no way to make 3rd Party apps work with the sensors because it's considered an Apple TV rather than button and sensors? I can make a new thread.

Not sure what you mean exactly. Please open an issue for that.

**Comment by dbsqp** [comment]
Been trying to work on this issue.

Firstly can use atvremote directly from within my homebridge docker container with no issue between subnets via atvremote --id <MAC> i.e. router mDNS is OK. Pair and then control all good. Issue is thus not pyatv/LAN.

```
[laptop:~]> nas
[nas:/volume1]>> sudo docker exec -it Homebridge /bin/bash
Password: 
Note: This is a restricted shell, sudo cannot be used here.

Homebridge Terminal

Node.js Version: v20.18.0
Node.js Path: /opt/homebridge/bin/node
Plugin Path: /var/lib/homebridge/node_modules

Update Node.js: hb-service update-node

Install Plugin: hb-service add homebridge-plugin-name
Remove Plugin: hb-service remove homebridge-plugin-name

root@Homebridge:/homebridge $ python3 --version
Python 3.10.12
root@Homebridge:/homebridge $ atvremote --version
atvremote 0.16.0
root@Homebridge:/homebridge $ atvremote --id 52:17:BF:12:9C:30 device_info
Model/SW: Apple TV 4K (gen 2), tvOS 18.1 build 22J580
     MAC: 52:17:BF:12:9C:30
root@Homebridge:/homebridge $ atvremote --id 52:17:BF:12:9C:30 power_state
PowerState.Off
root@Homebridge:/homebridge $ atvremote --id 52:17:BF:12:9C:30 app_list
App: Channel 4 (uk.co.channel4.ios.4od), App: Fitness (com.apple.Fitness), App: Podcasts (com.apple.podcasts), App: Movies (com.apple.TVMovies), App: TV (com.apple.TVWatchList), App: Photos (com.apple.TVPhotos), App: App Store (com.apple.TVAppStore), App: My5 (com.channel5.demand5), App: ORF ON (com.nousguide.ios.TVThek), App: BBC iPlayer (uk.co.bbc.iplayer), App: Arcade (com.apple.Arcade), App: Search (com.apple.TVSearch), App: Computers (com.apple.TVHomeSharing), App: FaceTime (com.apple.facetime), App: YouTube (com.google.ios.youtube), App: Plex (com.plexapp.plex), App: ServusTV On (com.redbull.ServusTV), App: ITVX (com.itv.itvplayer), App: Settings (com.apple.TVSettings), App: Music (com.apple.TVMusic), App: RetroArch (com.libretro.dist.RetroArch)

```


Pairing across subnets can be fixed by editing appleTVEnhancedAccessory.js to use id/mac not host/ip:

```
94 const pairingRequired = async () => {
95 // return this.pair(this.device.host, this.device.name).then((c) => {
96    return this.pair(this.device.host, this.device.mac, this.device.name).then((c) => {

1249 // async pair(ip, appleTVName) {
1250    async pair(ip, mac, appleTVName) {

1301 const process = (0, child_process_1.spawn)(CustomPyAtvInstance_1.default.getAtvremotePath(), [
1302 // '--host', host,
1303    '--id', mac,
```

Let me know if you want me to fork/pull but is trivial change and I doubt would impact same subnet implementations.

However still errors out with:

```
[12/4/2024, 11:46:48 PM] [Apple TV] [D] Living Room Apple TV (52:17:BF:12:9C:30): Error: Unexpected atvremote response: 2024-12-04 23:46:47 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network
    at A.listApps (/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/device.ts:499:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppleTVEnhancedAccessory.credentialsValid (/homebridge/node_modules/homebridge-appletv-enhanced/src/appleTVEnhancedAccessory.ts:913:17)

[12/4/2024, 11:46:48 PM] [Apple TV] [E] Living Room Apple TV (52:17:BF:12:9C:30): Apple TV can be reached on OSI Layer 2 but not on 3. This is likely a network problem. Restart the plugin after you have fixed the root cause. Enable debug logging to see the original errors.

```

I think this might be an issue with the initialisation of node-pyatv using host/ip and not id/mac.

From your side after this rocketremote.js is calling atvremote --id <MAC> so should work.

**Comment by maxileith** [comment]
I've opened an issue on node-pyatv regarding this topic: https://github.com/sebbo2002/node-pyatv/issues/353

**Comment by maxileith** [comment]
Hi @ivyrze,

can you try whether or not v1.13.0-0 works on your multi subnet setup?

Thanks in advance.

**Comment by maxileith** [comment]
@ivyrze thanks for the feedback
